var hierarchy =
[
    [ "Amuse::Core::AABB", "d0/d8d/struct_amuse_1_1_core_1_1_a_a_b_b.html", null ],
    [ "Amuse::Core::Allocator", "da/dba/class_amuse_1_1_core_1_1_allocator.html", null ],
    [ "Amuse::Core::Any", "d3/d9a/class_amuse_1_1_core_1_1_any.html", null ],
    [ "Amuse::Core::ArgumentInfo", "d7/dbc/struct_amuse_1_1_core_1_1_argument_info.html", null ],
    [ "Amuse::Platform::Arguments", "d5/d31/class_amuse_1_1_platform_1_1_arguments.html", null ],
    [ "Amuse::Core::AsyncFile", "d3/dd2/class_amuse_1_1_core_1_1_async_file.html", null ],
    [ "Amuse::Core::AsyncFileEvent", "d3/d41/class_amuse_1_1_core_1_1_async_file_event.html", null ],
    [ "Amuse::Core::AsyncFileHandle", "d3/d43/class_amuse_1_1_core_1_1_async_file_handle.html", null ],
    [ "Amuse::Core::AsyncFileQueue", "d8/da8/class_amuse_1_1_core_1_1_async_file_queue.html", null ],
    [ "Amuse::Core::AsyncFileRequest", "dd/dae/struct_amuse_1_1_core_1_1_async_file_request.html", null ],
    [ "Amuse::Input::Axis", "d8/d4e/class_amuse_1_1_input_1_1_axis.html", null ],
    [ "Amuse::RHI::BeginPassParam", "d5/d8d/struct_amuse_1_1_r_h_i_1_1_begin_pass_param.html", null ],
    [ "Amuse::Core::BinaryReader", "d5/d77/class_amuse_1_1_core_1_1_binary_reader.html", null ],
    [ "Amuse::Core::BinaryWriter", "d2/d17/class_amuse_1_1_core_1_1_binary_writer.html", null ],
    [ "Amuse::RHI::Binding", "d5/d13/struct_amuse_1_1_r_h_i_1_1_binding.html", null ],
    [ "Amuse::RHI::BindingItem", "d7/d74/struct_amuse_1_1_r_h_i_1_1_binding_item.html", null ],
    [ "Amuse::RHI::BindlessHandle", "d4/d5b/struct_amuse_1_1_r_h_i_1_1_bindless_handle.html", null ],
    [ "Amuse::Core::BitFlags&lt; TEnum, TBitsType &gt;", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::Bitmap", "d6/d91/class_amuse_1_1_core_1_1_bitmap.html", null ],
    [ "Amuse::Core::BitOp", "dc/df9/struct_amuse_1_1_core_1_1_bit_op.html", null ],
    [ "Amuse::RHI::BlendDesc", "d2/df6/struct_amuse_1_1_r_h_i_1_1_blend_desc.html", null ],
    [ "Amuse::Core::Blob", "df/d96/class_amuse_1_1_core_1_1_blob.html", null ],
    [ "Amuse::Core::BlobView", "d6/d80/class_amuse_1_1_core_1_1_blob_view.html", null ],
    [ "Amuse::Core::Bounds", "d3/d82/struct_amuse_1_1_core_1_1_bounds.html", null ],
    [ "Amuse::Core::Box", "d4/d7d/struct_amuse_1_1_core_1_1_box.html", null ],
    [ "Amuse::RHI::BufferBarrier", "d0/d0b/struct_amuse_1_1_r_h_i_1_1_buffer_barrier.html", null ],
    [ "Amuse::RHI::BufferCopyRegion", "d0/d8e/struct_amuse_1_1_r_h_i_1_1_buffer_copy_region.html", null ],
    [ "Amuse::RHI::BufferDesc", "d7/dab/struct_amuse_1_1_r_h_i_1_1_buffer_desc.html", null ],
    [ "Amuse::RHI::GraphicFileRequest::BufferDesc", "de/d62/struct_amuse_1_1_r_h_i_1_1_graphic_file_request_1_1_buffer_desc.html", null ],
    [ "Amuse::RHI::BufferTextureCopyRegion", "dd/d41/struct_amuse_1_1_r_h_i_1_1_buffer_texture_copy_region.html", null ],
    [ "Amuse::RHI::BufferViewDesc", "d7/d1b/struct_amuse_1_1_r_h_i_1_1_buffer_view_desc.html", null ],
    [ "Amuse::Input::Button", "db/dab/class_amuse_1_1_input_1_1_button.html", null ],
    [ "Amuse::Core::Capsule", "d9/da8/struct_amuse_1_1_core_1_1_capsule.html", null ],
    [ "Amuse::Core::Circle", "db/d9f/struct_amuse_1_1_core_1_1_circle.html", null ],
    [ "Amuse::Core::ClassTrait&lt; T &gt;", "de/d38/class_amuse_1_1_core_1_1_class_trait.html", null ],
    [ "Amuse::RHI::ClearColor", "dc/d68/struct_amuse_1_1_r_h_i_1_1_clear_color.html", null ],
    [ "Amuse::Core::Color", "d9/de4/struct_amuse_1_1_core_1_1_color.html", null ],
    [ "Amuse::RHI::CommandListDesc", "d8/d93/struct_amuse_1_1_r_h_i_1_1_command_list_desc.html", null ],
    [ "Amuse::Core::ComponentHolder&lt; T &gt;", "d5/df2/class_amuse_1_1_core_1_1_component_holder.html", null ],
    [ "Amuse::Core::ComponentManager&lt; T &gt;", "d8/d02/class_amuse_1_1_core_1_1_component_manager.html", null ],
    [ "Amuse::Core::Compression", "de/de3/class_amuse_1_1_core_1_1_compression.html", null ],
    [ "Amuse::RHI::ComputePipelineStateDesc", "d2/dbc/struct_amuse_1_1_r_h_i_1_1_compute_pipeline_state_desc.html", null ],
    [ "Amuse::Core::HandleForwardList&lt; T &gt;::const_iterator", "d4/d7f/class_amuse_1_1_core_1_1_handle_forward_list_1_1const__iterator.html", [
      [ "Amuse::Core::HandleForwardList< T >::iterator", "d0/dce/class_amuse_1_1_core_1_1_handle_forward_list_1_1iterator.html", null ]
    ] ],
    [ "Amuse::Core::HandleList&lt; T &gt;::const_iterator", "d3/de2/class_amuse_1_1_core_1_1_handle_list_1_1const__iterator.html", [
      [ "Amuse::Core::HandleList< T >::iterator", "d4/d5c/class_amuse_1_1_core_1_1_handle_list_1_1iterator.html", null ]
    ] ],
    [ "Amuse::Core::ConstValue&lt; T, N &gt;", "df/d46/struct_amuse_1_1_core_1_1_const_value.html", null ],
    [ "Amuse::RHI::CopyTextureParam", "d4/dc4/struct_amuse_1_1_r_h_i_1_1_copy_texture_param.html", null ],
    [ "Amuse::RPI::MeshRenderFeature::MeshViewData::CPUData", "d5/d9f/struct_amuse_1_1_r_p_i_1_1_mesh_render_feature_1_1_mesh_view_data_1_1_c_p_u_data.html", null ],
    [ "Amuse::Core::CRCHash", "d6/d57/class_amuse_1_1_core_1_1_c_r_c_hash.html", null ],
    [ "Amuse::Core::Cylinder", "dc/d5d/struct_amuse_1_1_core_1_1_cylinder.html", null ],
    [ "Amuse::Core::DateTime", "df/def/struct_amuse_1_1_core_1_1_date_time.html", null ],
    [ "Amuse::RPI::DeferredData", "db/d45/struct_amuse_1_1_r_p_i_1_1_deferred_data.html", null ],
    [ "Amuse::Core::Delegate&lt; R(Args...), BufferSize &gt;", "d6/d24/class_amuse_1_1_core_1_1_delegate_3_01_r_07_args_8_8_8_08_00_01_buffer_size_01_4.html", null ],
    [ "Amuse::RHI::DepthStencilDesc", "db/d85/struct_amuse_1_1_r_h_i_1_1_depth_stencil_desc.html", null ],
    [ "Amuse::RPI::ResizableBuffer::Desc", "d3/d09/struct_amuse_1_1_r_p_i_1_1_resizable_buffer_1_1_desc.html", null ],
    [ "Amuse::RHI::DescriptorLayoutDesc", "d5/d72/struct_amuse_1_1_r_h_i_1_1_descriptor_layout_desc.html", null ],
    [ "Amuse::RHI::DescriptorTableDesc", "d4/df3/struct_amuse_1_1_r_h_i_1_1_descriptor_table_desc.html", null ],
    [ "Amuse::RHI::DeviceAdapterInfo", "d9/d41/struct_amuse_1_1_r_h_i_1_1_device_adapter_info.html", null ],
    [ "Amuse::Input::DirectInput", "df/dba/class_amuse_1_1_input_1_1_direct_input.html", null ],
    [ "Amuse::RPI::DirectionalLightData", "d9/d79/struct_amuse_1_1_r_p_i_1_1_directional_light_data.html", null ],
    [ "Amuse::Core::Directory", "d8/d6b/class_amuse_1_1_core_1_1_directory.html", null ],
    [ "Amuse::RHI::DirectX12RHIConfig", "da/dbf/struct_amuse_1_1_r_h_i_1_1_direct_x12_r_h_i_config.html", null ],
    [ "Amuse::RHI::DispatchParam", "d4/d76/struct_amuse_1_1_r_h_i_1_1_dispatch_param.html", null ],
    [ "Amuse::Platform::DLL", "d7/d41/class_amuse_1_1_platform_1_1_d_l_l.html", null ],
    [ "Amuse::RHI::DrawIndexedParam", "d4/dc3/struct_amuse_1_1_r_h_i_1_1_draw_indexed_param.html", null ],
    [ "Amuse::RHI::DrawParam", "d7/d99/struct_amuse_1_1_r_h_i_1_1_draw_param.html", null ],
    [ "Amuse::Core::Easing", "d0/da0/class_amuse_1_1_core_1_1_easing.html", null ],
    [ "Amuse::Core::Endian", "db/d2a/class_amuse_1_1_core_1_1_endian.html", null ],
    [ "Amuse::Core::ErrorCode", "d2/d73/class_amuse_1_1_core_1_1_error_code.html", null ],
    [ "std::exception", null, [
      [ "Amuse::Core::Exception", "d7/de5/class_amuse_1_1_core_1_1_exception.html", [
        [ "Amuse::Core::ArgumentException", "df/d88/class_amuse_1_1_core_1_1_argument_exception.html", null ],
        [ "Amuse::Core::ArithmeticException", "d8/d20/class_amuse_1_1_core_1_1_arithmetic_exception.html", null ],
        [ "Amuse::Core::FormatException", "d2/de8/class_amuse_1_1_core_1_1_format_exception.html", null ],
        [ "Amuse::Core::InvalidOperationException", "de/dd8/class_amuse_1_1_core_1_1_invalid_operation_exception.html", null ],
        [ "Amuse::Core::KeyNotFoundException", "d9/d80/class_amuse_1_1_core_1_1_key_not_found_exception.html", null ],
        [ "Amuse::Core::NotImplementedException", "d8/dcb/class_amuse_1_1_core_1_1_not_implemented_exception.html", null ],
        [ "Amuse::Core::NotSupportedException", "d9/dc4/class_amuse_1_1_core_1_1_not_supported_exception.html", null ],
        [ "Amuse::Core::OutOfRangeException", "df/dde/class_amuse_1_1_core_1_1_out_of_range_exception.html", null ],
        [ "Amuse::Core::PathNotFoundException", "d7/d5f/class_amuse_1_1_core_1_1_path_not_found_exception.html", null ],
        [ "Amuse::Core::XmlException", "da/d0a/class_amuse_1_1_core_1_1_xml_exception.html", null ]
      ] ]
    ] ],
    [ "std::false_type", null, [
      [ "Amuse::Core::is_map< HashMap< TKey, TValue > >", "dc/d63/struct_amuse_1_1_core_1_1is__map_3_01_hash_map_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
      [ "Amuse::Core::is_map< Map< TKey, TValue > >", "d8/da4/struct_amuse_1_1_core_1_1is__map_3_01_map_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< Array< T, N > >", "d4/d8c/struct_amuse_1_1_core_1_1is__sequence_3_01_array_3_01_t_00_01_n_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< HashSet< T, ALLOCATOR > >", "dd/d3c/struct_amuse_1_1_core_1_1is__sequence_3_01_hash_set_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< List< T, ALLOCATOR > >", "d6/d92/struct_amuse_1_1_core_1_1is__sequence_3_01_list_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< Set< T, ALLOCATOR > >", "d1/dfc/struct_amuse_1_1_core_1_1is__sequence_3_01_set_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< T[N]>", "d6/d8f/struct_amuse_1_1_core_1_1is__sequence_3_01_t_0f_n_0e_4.html", null ],
      [ "Amuse::Core::is_sequence< Vector< T, ALLOCATOR > >", "da/d1b/struct_amuse_1_1_core_1_1is__sequence_3_01_vector_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_iterator< class, class >", "d8/d3d/struct_amuse_1_1_core_1_1is__iterator.html", null ],
      [ "Amuse::Core::is_map< T >", "d2/d16/struct_amuse_1_1_core_1_1is__map.html", null ],
      [ "Amuse::Core::is_sequence< T >", "d3/dfb/struct_amuse_1_1_core_1_1is__sequence.html", null ]
    ] ],
    [ "Amuse::RHI::FenceDesc", "dd/ded/struct_amuse_1_1_r_h_i_1_1_fence_desc.html", null ],
    [ "Amuse::RPI::FGBuilder", "d2/d00/class_amuse_1_1_r_p_i_1_1_f_g_builder.html", null ],
    [ "Amuse::RPI::FGConnections", "de/dd3/class_amuse_1_1_r_p_i_1_1_f_g_connections.html", null ],
    [ "Amuse::RPI::FGData", "d0/dc2/struct_amuse_1_1_r_p_i_1_1_f_g_data.html", null ],
    [ "Amuse::RPI::FGDataWriter", "d9/d5c/class_amuse_1_1_r_p_i_1_1_f_g_data_writer.html", null ],
    [ "Amuse::RPI::FGResource", "d1/dca/struct_amuse_1_1_r_p_i_1_1_f_g_resource.html", null ],
    [ "Amuse::RPI::FGResources", "dd/dcd/class_amuse_1_1_r_p_i_1_1_f_g_resources.html", null ],
    [ "Amuse::Core::FixedFunc&lt; R(Args...), BufferSize &gt;", "d4/db1/class_amuse_1_1_core_1_1_fixed_func_3_01_r_07_args_8_8_8_08_00_01_buffer_size_01_4.html", null ],
    [ "Amuse::Core::FixedStringBase&lt; TChar, N &gt;", "d4/ddd/class_amuse_1_1_core_1_1_fixed_string_base.html", null ],
    [ "Amuse::Core::FixedVector&lt; T, N &gt;", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FloatCompression", "da/d8a/class_amuse_1_1_core_1_1_float_compression.html", null ],
    [ "ImPlot::Formatter_Time_Data", "db/dbe/struct_im_plot_1_1_formatter___time___data.html", null ],
    [ "Amuse::Core::Frustum", "db/d2e/struct_amuse_1_1_core_1_1_frustum.html", null ],
    [ "Amuse::Core::GDeflate", "d4/dbe/class_amuse_1_1_core_1_1_g_deflate.html", null ],
    [ "Amuse::Core::Global&lt; T &gt;", "d7/d77/class_amuse_1_1_core_1_1_global.html", null ],
    [ "Amuse::RPI::MeshRenderFeature::MeshViewData::GPUData", "da/d75/struct_amuse_1_1_r_p_i_1_1_mesh_render_feature_1_1_mesh_view_data_1_1_g_p_u_data.html", null ],
    [ "Amuse::RHI::GraphicFile", "da/d89/class_amuse_1_1_r_h_i_1_1_graphic_file.html", null ],
    [ "Amuse::RHI::GraphicFileMipInfo", "d8/d14/struct_amuse_1_1_r_h_i_1_1_graphic_file_mip_info.html", null ],
    [ "Amuse::RHI::GraphicFileQueueDesc", "d2/dbf/struct_amuse_1_1_r_h_i_1_1_graphic_file_queue_desc.html", null ],
    [ "Amuse::RHI::GraphicFileRequest", "d7/dc9/struct_amuse_1_1_r_h_i_1_1_graphic_file_request.html", null ],
    [ "Amuse::Core::HalfLine", "db/d03/class_amuse_1_1_core_1_1_half_line.html", null ],
    [ "Amuse::Core::Handle&lt; T, TNamespace &gt;", "d3/d60/class_amuse_1_1_core_1_1_handle.html", null ],
    [ "Amuse::Core::HandleManager&lt; T, Deleter &gt;::Handle", "db/dbd/class_amuse_1_1_core_1_1_handle_manager_1_1_handle.html", null ],
    [ "Amuse::RPI::SparseUploadBuffer&lt; T &gt;::Handle", "d1/d93/class_amuse_1_1_r_p_i_1_1_sparse_upload_buffer_1_1_handle.html", null ],
    [ "HandleBase", null, [
      [ "Amuse::Core::HandleForwardList< T >::Handle", "dc/d57/class_amuse_1_1_core_1_1_handle_forward_list_1_1_handle.html", null ]
    ] ],
    [ "Amuse::Core::HandleManager&lt; T, Deleter &gt;", "da/d02/class_amuse_1_1_core_1_1_handle_manager.html", null ],
    [ "Amuse::Core::Hash", "d5/d6f/class_amuse_1_1_core_1_1_hash.html", null ],
    [ "Amuse::Core::SyncHandleManager&lt; T, Deleter &gt;::Hasher", "d0/df7/struct_amuse_1_1_core_1_1_sync_handle_manager_1_1_hasher.html", null ],
    [ "Amuse::Core::HSV", "d3/d4e/struct_amuse_1_1_core_1_1_h_s_v.html", null ],
    [ "Amuse::Input::IInputDevice", "dc/dcb/class_amuse_1_1_input_1_1_i_input_device.html", null ],
    [ "ImBitArray&lt; BITCOUNT, OFFSET &gt;", "d6/d40/struct_im_bit_array.html", null ],
    [ "ImBitVector", "d6/d28/struct_im_bit_vector.html", null ],
    [ "ImChunkStream&lt; T &gt;", "d0/d05/struct_im_chunk_stream.html", null ],
    [ "ImColor", "db/da3/struct_im_color.html", null ],
    [ "ImDrawChannel", "df/d94/struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "d6/d65/struct_im_draw_cmd.html", null ],
    [ "ImDrawCmdHeader", "d0/de9/struct_im_draw_cmd_header.html", null ],
    [ "ImDrawData", "d9/d78/struct_im_draw_data.html", null ],
    [ "ImDrawDataBuilder", "de/d11/struct_im_draw_data_builder.html", null ],
    [ "ImDrawList", "dd/d30/struct_im_draw_list.html", null ],
    [ "ImDrawListSharedData", "dd/d70/struct_im_draw_list_shared_data.html", null ],
    [ "ImDrawListSplitter", "d4/de1/struct_im_draw_list_splitter.html", null ],
    [ "ImDrawVert", "dc/d86/struct_im_draw_vert.html", null ],
    [ "ImFont", "d7/dc9/struct_im_font.html", null ],
    [ "ImFontAtlas", "d5/d9e/struct_im_font_atlas.html", null ],
    [ "ImFontAtlasCustomRect", "d1/d27/struct_im_font_atlas_custom_rect.html", null ],
    [ "ImFontBuilderIO", "d3/d0e/struct_im_font_builder_i_o.html", null ],
    [ "ImFontConfig", "d5/d84/struct_im_font_config.html", null ],
    [ "ImFontGlyph", "df/d57/struct_im_font_glyph.html", null ],
    [ "ImFontGlyphRangesBuilder", "d4/d56/struct_im_font_glyph_ranges_builder.html", null ],
    [ "ImGuiColorMod", "da/d8e/struct_im_gui_color_mod.html", null ],
    [ "ImGuiComboPreviewData", "d7/d3a/struct_im_gui_combo_preview_data.html", null ],
    [ "ImGuiContext", "d7/da3/struct_im_gui_context.html", null ],
    [ "ImGuiContextHook", "df/dbc/struct_im_gui_context_hook.html", null ],
    [ "ImGuiDataTypeInfo", "d5/dbe/struct_im_gui_data_type_info.html", null ],
    [ "ImGuiDataTypeStorage", "de/d93/struct_im_gui_data_type_storage.html", null ],
    [ "ImGuiDataVarInfo", "de/da3/struct_im_gui_data_var_info.html", null ],
    [ "ImGuiDebugAllocEntry", "dd/d28/struct_im_gui_debug_alloc_entry.html", null ],
    [ "ImGuiDebugAllocInfo", "d2/d45/struct_im_gui_debug_alloc_info.html", null ],
    [ "ImGuiFocusScopeData", "d5/d65/struct_im_gui_focus_scope_data.html", null ],
    [ "ImGuiGroupData", "da/dc1/struct_im_gui_group_data.html", null ],
    [ "ImGuiIDStackTool", "d7/d67/struct_im_gui_i_d_stack_tool.html", null ],
    [ "ImGuiInputEvent", "d7/d1b/struct_im_gui_input_event.html", null ],
    [ "ImGuiInputEventAppFocused", "d5/dd8/struct_im_gui_input_event_app_focused.html", null ],
    [ "ImGuiInputEventKey", "db/d5c/struct_im_gui_input_event_key.html", null ],
    [ "ImGuiInputEventMouseButton", "dc/dd8/struct_im_gui_input_event_mouse_button.html", null ],
    [ "ImGuiInputEventMousePos", "d7/d2b/struct_im_gui_input_event_mouse_pos.html", null ],
    [ "ImGuiInputEventMouseWheel", "d0/d89/struct_im_gui_input_event_mouse_wheel.html", null ],
    [ "ImGuiInputEventText", "d5/dca/struct_im_gui_input_event_text.html", null ],
    [ "ImGuiInputTextCallbackData", "da/d51/struct_im_gui_input_text_callback_data.html", null ],
    [ "ImGuiInputTextDeactivatedState", "d8/db2/struct_im_gui_input_text_deactivated_state.html", null ],
    [ "ImGuiInputTextState", "da/d59/struct_im_gui_input_text_state.html", null ],
    [ "ImGuiIO", "d5/dbc/struct_im_gui_i_o.html", null ],
    [ "ImGuiKeyData", "d2/dc3/struct_im_gui_key_data.html", null ],
    [ "ImGuiKeyOwnerData", "d6/d20/struct_im_gui_key_owner_data.html", null ],
    [ "ImGuiKeyRoutingData", "dc/d72/struct_im_gui_key_routing_data.html", null ],
    [ "ImGuiKeyRoutingTable", "d6/d75/struct_im_gui_key_routing_table.html", null ],
    [ "ImGuiLastItemData", "da/d5e/struct_im_gui_last_item_data.html", null ],
    [ "ImGuiListClipper", "df/d0a/struct_im_gui_list_clipper.html", null ],
    [ "ImGuiListClipperData", "df/dfc/struct_im_gui_list_clipper_data.html", null ],
    [ "ImGuiListClipperRange", "df/d46/struct_im_gui_list_clipper_range.html", null ],
    [ "ImGuiLocEntry", "d5/dbb/struct_im_gui_loc_entry.html", null ],
    [ "ImGuiMenuColumns", "dc/d02/struct_im_gui_menu_columns.html", null ],
    [ "ImGuiMetricsConfig", "d3/d28/struct_im_gui_metrics_config.html", null ],
    [ "ImGuiNavItemData", "de/d6f/struct_im_gui_nav_item_data.html", null ],
    [ "ImGuiNavTreeNodeData", "de/d29/struct_im_gui_nav_tree_node_data.html", null ],
    [ "ImGuiNextItemData", "de/d0e/struct_im_gui_next_item_data.html", null ],
    [ "ImGuiNextWindowData", "d3/dd8/struct_im_gui_next_window_data.html", null ],
    [ "ImGuiOldColumnData", "db/d99/struct_im_gui_old_column_data.html", null ],
    [ "ImGuiOldColumns", "de/ded/struct_im_gui_old_columns.html", null ],
    [ "ImGuiOnceUponAFrame", "d4/da6/struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPayload", "d7/d1d/struct_im_gui_payload.html", null ],
    [ "ImGuiPlatformImeData", "d8/dc8/struct_im_gui_platform_ime_data.html", null ],
    [ "ImGuiPopupData", "da/d23/struct_im_gui_popup_data.html", null ],
    [ "ImGuiPtrOrIndex", "d7/d84/struct_im_gui_ptr_or_index.html", null ],
    [ "ImGuiSettingsHandler", "d2/d98/struct_im_gui_settings_handler.html", null ],
    [ "ImGuiShrinkWidthItem", "db/d9d/struct_im_gui_shrink_width_item.html", null ],
    [ "ImGuiSizeCallbackData", "da/d8c/struct_im_gui_size_callback_data.html", null ],
    [ "ImGuiStackLevelInfo", "da/dd0/struct_im_gui_stack_level_info.html", null ],
    [ "ImGuiStackSizes", "da/d2e/struct_im_gui_stack_sizes.html", null ],
    [ "ImGuiStorage", "df/d15/struct_im_gui_storage.html", null ],
    [ "ImGuiStorage::ImGuiStoragePair", "dc/d48/struct_im_gui_storage_1_1_im_gui_storage_pair.html", null ],
    [ "ImGuiStyle", "d7/d12/struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "d4/df8/struct_im_gui_style_mod.html", null ],
    [ "ImGuiTabBar", "d5/d7d/struct_im_gui_tab_bar.html", null ],
    [ "ImGuiTabItem", "d3/d39/struct_im_gui_tab_item.html", null ],
    [ "ImGuiTable", "da/d11/struct_im_gui_table.html", null ],
    [ "ImGuiTableCellData", "d4/d22/struct_im_gui_table_cell_data.html", null ],
    [ "ImGuiTableColumn", "d7/d8b/struct_im_gui_table_column.html", null ],
    [ "ImGuiTableColumnSettings", "da/daa/struct_im_gui_table_column_settings.html", null ],
    [ "ImGuiTableColumnSortSpecs", "d4/d36/struct_im_gui_table_column_sort_specs.html", null ],
    [ "ImGuiTableHeaderData", "d8/dfa/struct_im_gui_table_header_data.html", null ],
    [ "ImGuiTableInstanceData", "dc/d0a/struct_im_gui_table_instance_data.html", null ],
    [ "ImGuiTableSettings", "d2/dd0/struct_im_gui_table_settings.html", null ],
    [ "ImGuiTableSortSpecs", "d2/d81/struct_im_gui_table_sort_specs.html", null ],
    [ "ImGuiTableTempData", "d1/d09/struct_im_gui_table_temp_data.html", null ],
    [ "ImGuiTextBuffer", "da/d7d/struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextFilter", "d5/de6/struct_im_gui_text_filter.html", null ],
    [ "ImGuiTextIndex", "df/d5b/struct_im_gui_text_index.html", null ],
    [ "ImGuiTextFilter::ImGuiTextRange", "d1/dde/struct_im_gui_text_filter_1_1_im_gui_text_range.html", null ],
    [ "ImGuiTypingSelectRequest", "d2/dee/struct_im_gui_typing_select_request.html", null ],
    [ "ImGuiTypingSelectState", "dd/dac/struct_im_gui_typing_select_state.html", null ],
    [ "ImGuiViewport", "d3/da6/struct_im_gui_viewport.html", [
      [ "ImGuiViewportP", "d7/dc4/struct_im_gui_viewport_p.html", null ]
    ] ],
    [ "ImGuiWindow", "d6/d8f/struct_im_gui_window.html", null ],
    [ "ImGuiWindowSettings", "d5/db5/struct_im_gui_window_settings.html", null ],
    [ "ImGuiWindowStackData", "d1/d7e/struct_im_gui_window_stack_data.html", null ],
    [ "ImGuiWindowTempData", "d3/d82/struct_im_gui_window_temp_data.html", null ],
    [ "ImNewWrapper", "dd/d6b/struct_im_new_wrapper.html", null ],
    [ "ImPlotAlignmentData", "d4/d08/struct_im_plot_alignment_data.html", null ],
    [ "ImPlotAnnotation", "d6/ddf/struct_im_plot_annotation.html", null ],
    [ "ImPlotAnnotationCollection", "db/d4a/struct_im_plot_annotation_collection.html", null ],
    [ "ImPlotAxis", "d9/dd2/struct_im_plot_axis.html", null ],
    [ "ImPlotColormapData", "d2/dba/struct_im_plot_colormap_data.html", null ],
    [ "ImPlotContext", "d2/d8a/struct_im_plot_context.html", null ],
    [ "ImPlotDateTimeSpec", "d5/d5a/struct_im_plot_date_time_spec.html", null ],
    [ "ImPlotInputMap", "dc/d0c/struct_im_plot_input_map.html", null ],
    [ "ImPlotItem", "df/dce/struct_im_plot_item.html", null ],
    [ "ImPlotItemGroup", "d5/dda/struct_im_plot_item_group.html", null ],
    [ "ImPlotLegend", "d8/d1b/struct_im_plot_legend.html", null ],
    [ "ImPlotNextItemData", "d4/dc0/struct_im_plot_next_item_data.html", null ],
    [ "ImPlotNextPlotData", "d0/de4/struct_im_plot_next_plot_data.html", null ],
    [ "ImPlotPlot", "dd/df5/struct_im_plot_plot.html", null ],
    [ "ImPlotPoint", "d9/d36/struct_im_plot_point.html", null ],
    [ "ImPlotPointError", "dd/db9/struct_im_plot_point_error.html", null ],
    [ "ImPlotRange", "d8/d09/struct_im_plot_range.html", null ],
    [ "ImPlotRect", "d4/dba/struct_im_plot_rect.html", null ],
    [ "ImPlotStyle", "d2/dd6/struct_im_plot_style.html", null ],
    [ "ImPlotSubplot", "d0/d57/struct_im_plot_subplot.html", null ],
    [ "ImPlotTag", "d9/dd9/struct_im_plot_tag.html", null ],
    [ "ImPlotTagCollection", "d8/d44/struct_im_plot_tag_collection.html", null ],
    [ "ImPlotTick", "dc/dd3/struct_im_plot_tick.html", null ],
    [ "ImPlotTicker", "d5/d35/struct_im_plot_ticker.html", null ],
    [ "ImPlotTime", "db/d5c/struct_im_plot_time.html", null ],
    [ "ImPool&lt; T &gt;", "d9/d6a/struct_im_pool.html", null ],
    [ "ImRect", "df/d8d/struct_im_rect.html", null ],
    [ "ImSpan&lt; T &gt;", "d0/dbe/struct_im_span.html", null ],
    [ "ImSpanAllocator&lt; CHUNKS &gt;", "d7/d2c/struct_im_span_allocator.html", null ],
    [ "ImVec1", "df/d59/struct_im_vec1.html", null ],
    [ "ImVec2", "d7/d55/struct_im_vec2.html", null ],
    [ "ImVec2ih", "d5/dc6/struct_im_vec2ih.html", null ],
    [ "ImVec4", "de/d2a/struct_im_vec4.html", null ],
    [ "ImVector&lt; T &gt;", "df/d93/struct_im_vector.html", null ],
    [ "Amuse::Core::IndexedVector&lt; T, TIndex, TDataVector, TIndexVector &gt;", "db/d95/class_amuse_1_1_core_1_1_indexed_vector.html", null ],
    [ "Amuse::Core::IndexMap&lt; TKey, TValue, THasher, TKeyEqual, TAllocator &gt;", "d7/ddc/class_amuse_1_1_core_1_1_index_map.html", null ],
    [ "Amuse::RHI::IndirectCommandParam", "d9/d89/struct_amuse_1_1_r_h_i_1_1_indirect_command_param.html", null ],
    [ "Amuse::Core::INI", "df/d76/class_amuse_1_1_core_1_1_i_n_i.html", null ],
    [ "Amuse::Core::INISection", "d4/d97/class_amuse_1_1_core_1_1_i_n_i_section.html", null ],
    [ "Amuse::RPI::DeferredPass::Input", "db/dfb/struct_amuse_1_1_r_p_i_1_1_deferred_pass_1_1_input.html", [
      [ "Amuse::RPI::DeferredPass::Output", "d8/da8/struct_amuse_1_1_r_p_i_1_1_deferred_pass_1_1_output.html", null ]
    ] ],
    [ "Amuse::RPI::EarlyZPass::Input", "d4/d8f/struct_amuse_1_1_r_p_i_1_1_early_z_pass_1_1_input.html", null ],
    [ "Amuse::RPI::GBufferPass::Input", "d9/df0/struct_amuse_1_1_r_p_i_1_1_g_buffer_pass_1_1_input.html", [
      [ "Amuse::RPI::GBufferPass::Output", "df/dee/struct_amuse_1_1_r_p_i_1_1_g_buffer_pass_1_1_output.html", null ]
    ] ],
    [ "Amuse::RPI::ImGuiPass::Input", "d8/df4/struct_amuse_1_1_r_p_i_1_1_im_gui_pass_1_1_input.html", null ],
    [ "Amuse::RPI::MaskedPass::Input", "d5/d8e/struct_amuse_1_1_r_p_i_1_1_masked_pass_1_1_input.html", [
      [ "Amuse::RPI::MaskedPass::Output", "dd/de3/struct_amuse_1_1_r_p_i_1_1_masked_pass_1_1_output.html", null ]
    ] ],
    [ "Amuse::RPI::OpaquePass::Input", "d5/dc9/struct_amuse_1_1_r_p_i_1_1_opaque_pass_1_1_input.html", [
      [ "Amuse::RPI::OpaquePass::Output", "d0/daf/struct_amuse_1_1_r_p_i_1_1_opaque_pass_1_1_output.html", null ]
    ] ],
    [ "Amuse::RPI::OutputPass::Input", "d1/d0e/struct_amuse_1_1_r_p_i_1_1_output_pass_1_1_input.html", [
      [ "Amuse::RPI::OutputPass::Output", "da/d15/struct_amuse_1_1_r_p_i_1_1_output_pass_1_1_output.html", null ]
    ] ],
    [ "Amuse::Input::InputConfig", "d0/d4b/struct_amuse_1_1_input_1_1_input_config.html", null ],
    [ "Amuse::RPI::InputLayout", "de/d05/struct_amuse_1_1_r_p_i_1_1_input_layout.html", null ],
    [ "Amuse::Core::IntColor", "dc/d7f/struct_amuse_1_1_core_1_1_int_color.html", null ],
    [ "Amuse::Core::IntRect", "d9/dbf/struct_amuse_1_1_core_1_1_int_rect.html", null ],
    [ "Amuse::Core::IntrusiveQueue&lt; T, pMember &gt;", "d4/d06/class_amuse_1_1_core_1_1_intrusive_queue.html", null ],
    [ "Amuse::Core::IntVec2", "d7/db0/struct_amuse_1_1_core_1_1_int_vec2.html", null ],
    [ "Amuse::Core::IntVec3", "df/db7/struct_amuse_1_1_core_1_1_int_vec3.html", null ],
    [ "Amuse::Core::IntVec4", "d8/dad/struct_amuse_1_1_core_1_1_int_vec4.html", null ],
    [ "Amuse::Core::IPAddress", "d0/da8/struct_amuse_1_1_core_1_1_i_p_address.html", null ],
    [ "Amuse::Core::StringSplitView::Iterator", "d3/df8/class_amuse_1_1_core_1_1_string_split_view_1_1_iterator.html", null ],
    [ "Amuse::Core::JobGroup", "d0/d57/class_amuse_1_1_core_1_1_job_group.html", null ],
    [ "Amuse::Input::Keyboard", "df/d41/class_amuse_1_1_input_1_1_keyboard.html", null ],
    [ "Amuse::Core::Line", "de/d82/struct_amuse_1_1_core_1_1_line.html", null ],
    [ "Amuse::Core::Locale", "db/d8d/class_amuse_1_1_core_1_1_locale.html", null ],
    [ "Amuse::RPI::MeshRenderFeature::MeshViewData::CPUData::Unit::LOD", "dd/d97/struct_amuse_1_1_r_p_i_1_1_mesh_render_feature_1_1_mesh_view_data_1_1_c_p_u_data_1_1_unit_1_1_l_o_d.html", null ],
    [ "Amuse::Core::Log", "d3/dfd/struct_amuse_1_1_core_1_1_log.html", null ],
    [ "Amuse::Core::Logger", "d6/ded/class_amuse_1_1_core_1_1_logger.html", null ],
    [ "Amuse::Core::Margin", "d4/d7f/struct_amuse_1_1_core_1_1_margin.html", null ],
    [ "Amuse::RPI::MaterialSystem::MateriaBlockDescSet", "db/dd1/struct_amuse_1_1_r_p_i_1_1_material_system_1_1_materia_block_desc_set.html", null ],
    [ "Amuse::RPI::MaterialBlock", "d2/d14/class_amuse_1_1_r_p_i_1_1_material_block.html", null ],
    [ "Amuse::RPI::MaterialBlockDesc", "de/d15/struct_amuse_1_1_r_p_i_1_1_material_block_desc.html", null ],
    [ "Amuse::RPI::MaterialBlockSet", "db/d34/struct_amuse_1_1_r_p_i_1_1_material_block_set.html", null ],
    [ "Amuse::RPI::MaterialDesc", "d2/d92/struct_amuse_1_1_r_p_i_1_1_material_desc.html", null ],
    [ "Amuse::RPI::MaterialDrawItem", "dc/d6e/struct_amuse_1_1_r_p_i_1_1_material_draw_item.html", null ],
    [ "Amuse::RPI::MaterialDrawPacket", "d4/d39/struct_amuse_1_1_r_p_i_1_1_material_draw_packet.html", null ],
    [ "Amuse::RPI::MaterialDrawPass", "dc/d9d/struct_amuse_1_1_r_p_i_1_1_material_draw_pass.html", null ],
    [ "Amuse::RPI::MaterialSystem::MaterialLayoutSet", "d9/d30/struct_amuse_1_1_r_p_i_1_1_material_system_1_1_material_layout_set.html", null ],
    [ "Amuse::RPI::MaterialPass", "dc/de5/struct_amuse_1_1_r_p_i_1_1_material_pass.html", null ],
    [ "Amuse::RPI::MaterialPropertiesDesc", "d8/df0/struct_amuse_1_1_r_p_i_1_1_material_properties_desc.html", null ],
    [ "Amuse::RPI::MaterialPropertiesSetDesc", "d9/d4e/struct_amuse_1_1_r_p_i_1_1_material_properties_set_desc.html", null ],
    [ "Amuse::RPI::MaterialSystemDesc", "d8/d7c/struct_amuse_1_1_r_p_i_1_1_material_system_desc.html", null ],
    [ "Amuse::RPI::MaterialValuePropertyDesc", "d4/d56/struct_amuse_1_1_r_p_i_1_1_material_value_property_desc.html", null ],
    [ "Amuse::RPI::MaterialViewData", "d4/dd1/struct_amuse_1_1_r_p_i_1_1_material_view_data.html", null ],
    [ "Amuse::Core::Math", "df/d2e/class_amuse_1_1_core_1_1_math.html", null ],
    [ "Amuse::Core::Matrix", "dc/d67/struct_amuse_1_1_core_1_1_matrix.html", null ],
    [ "Amuse::Core::MemorySize", "d5/d1f/struct_amuse_1_1_core_1_1_memory_size.html", null ],
    [ "Amuse::RPI::MeshRenderFeature::MeshCommand", "db/d4a/struct_amuse_1_1_r_p_i_1_1_mesh_render_feature_1_1_mesh_command.html", null ],
    [ "Amuse::RPI::MeshLod", "de/df5/struct_amuse_1_1_r_p_i_1_1_mesh_lod.html", null ],
    [ "Amuse::RPI::MeshLodBuffer", "d8/d20/struct_amuse_1_1_r_p_i_1_1_mesh_lod_buffer.html", null ],
    [ "Amuse::RPI::MeshLodSource", "de/d79/struct_amuse_1_1_r_p_i_1_1_mesh_lod_source.html", null ],
    [ "Amuse::RPI::MeshProxy", "d0/d4d/struct_amuse_1_1_r_p_i_1_1_mesh_proxy.html", null ],
    [ "Amuse::RPI::MeshSection", "de/db8/struct_amuse_1_1_r_p_i_1_1_mesh_section.html", null ],
    [ "Amuse::RPI::MeshUnitKey", "d2/dfc/struct_amuse_1_1_r_p_i_1_1_mesh_unit_key.html", null ],
    [ "Amuse::RPI::MeshUnitKeyHasher", "d5/dc0/struct_amuse_1_1_r_p_i_1_1_mesh_unit_key_hasher.html", null ],
    [ "Amuse::Core::MiniDelegate&lt; R(Args...)&gt;", "d2/d16/class_amuse_1_1_core_1_1_mini_delegate_3_01_r_07_args_8_8_8_08_4.html", null ],
    [ "Amuse::Input::Mouse", "dd/d1c/class_amuse_1_1_input_1_1_mouse.html", null ],
    [ "Amuse::Core::MTL", "dc/d59/class_amuse_1_1_core_1_1_m_t_l.html", null ],
    [ "Amuse::Core::Name", "d0/d53/class_amuse_1_1_core_1_1_name.html", null ],
    [ "Amuse::Core::Network", "d9/d11/class_amuse_1_1_core_1_1_network.html", null ],
    [ "Amuse::RPI::FG::NoData", "d4/d78/struct_amuse_1_1_r_p_i_1_1_f_g_1_1_no_data.html", null ],
    [ "Amuse::Core::HandleManager&lt; T, Deleter &gt;::Node", "d6/d5d/struct_amuse_1_1_core_1_1_handle_manager_1_1_node.html", null ],
    [ "Amuse::Core::Noise", "d4/d41/class_amuse_1_1_core_1_1_noise.html", null ],
    [ "Amuse::Core::Noncopyable", "dc/d43/class_amuse_1_1_core_1_1_noncopyable.html", [
      [ "Amuse::Core::EventNotifier< const Log & >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::EventNotifier< Args... >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::EventNotifier<>", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::EventNotifier< f32 >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::EventNotifier< const WindowEventArgs & >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::difference_type< T >", "d3/ddf/class_amuse_1_1_core_1_1_handle_forward_list.html", null ],
      [ "Amuse::Core::const_iterator< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::difference_type< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::HandleList< delegate_type >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::MemoryStorageBase< T, sizeof(T), alignof(T)>", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 128, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 32, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::AnyContainer", "d3/daa/class_amuse_1_1_core_1_1_any_container.html", null ],
      [ "Amuse::Core::EventNotifier< Args >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::HandleForwardList< T >", "d3/ddf/class_amuse_1_1_core_1_1_handle_forward_list.html", null ],
      [ "Amuse::Core::HandleForwardList< T >::Handle", "dc/d57/class_amuse_1_1_core_1_1_handle_forward_list_1_1_handle.html", null ],
      [ "Amuse::Core::HandleList< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::HandleList< T >::Handle", "dd/d26/class_amuse_1_1_core_1_1_handle_list_1_1_handle.html", null ],
      [ "Amuse::Core::JobGroupHandle", "dc/d1f/class_amuse_1_1_core_1_1_job_group_handle.html", null ],
      [ "Amuse::Core::JobHandle", "da/d98/class_amuse_1_1_core_1_1_job_handle.html", null ],
      [ "Amuse::Core::MemoryStorageBase< T, SIZE, ALIGN >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::Mutex", "d5/d20/class_amuse_1_1_core_1_1_mutex.html", null ],
      [ "Amuse::Core::ScopeLock< TLockable >", "dd/df1/class_amuse_1_1_core_1_1_scope_lock.html", null ],
      [ "Amuse::Core::SpinLock", "d1/db6/class_amuse_1_1_core_1_1_spin_lock.html", null ],
      [ "Amuse::Core::TLSFMapper", "dc/d9f/class_amuse_1_1_core_1_1_t_l_s_f_mapper.html", null ],
      [ "Amuse::Core::Thread", "d4/dc8/class_amuse_1_1_core_1_1_thread.html", null ],
      [ "Amuse::RPI::FG", "d7/d93/class_amuse_1_1_r_p_i_1_1_f_g.html", null ]
    ] ],
    [ "Amuse::Core::Nonmovable", "d6/d34/class_amuse_1_1_core_1_1_nonmovable.html", [
      [ "Amuse::Core::const_iterator< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::difference_type< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::HandleList< delegate_type >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::MemoryStorageBase< T, sizeof(T), alignof(T)>", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 128, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 32, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::AnyContainer", "d3/daa/class_amuse_1_1_core_1_1_any_container.html", null ],
      [ "Amuse::Core::HandleForwardList< T >::Handle", "dc/d57/class_amuse_1_1_core_1_1_handle_forward_list_1_1_handle.html", null ],
      [ "Amuse::Core::HandleList< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::HandleList< T >::Handle", "dd/d26/class_amuse_1_1_core_1_1_handle_list_1_1_handle.html", null ],
      [ "Amuse::Core::JobGroupHandle", "dc/d1f/class_amuse_1_1_core_1_1_job_group_handle.html", null ],
      [ "Amuse::Core::JobHandle", "da/d98/class_amuse_1_1_core_1_1_job_handle.html", null ],
      [ "Amuse::Core::MemoryStorageBase< T, SIZE, ALIGN >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::ThreadLocalContext< T >", "da/d56/class_amuse_1_1_core_1_1_thread_local_context.html", null ],
      [ "Amuse::RPI::FG", "d7/d93/class_amuse_1_1_r_p_i_1_1_f_g.html", null ]
    ] ],
    [ "Amuse::Core::OBB", "d9/d95/struct_amuse_1_1_core_1_1_o_b_b.html", null ],
    [ "Amuse::Core::OBJ", "d4/d75/class_amuse_1_1_core_1_1_o_b_j.html", null ],
    [ "Amuse::RPI::EarlyZPass::Output", "d8/d38/struct_amuse_1_1_r_p_i_1_1_early_z_pass_1_1_output.html", null ],
    [ "Amuse::RPI::ImGuiPass::Output", "df/d1d/struct_amuse_1_1_r_p_i_1_1_im_gui_pass_1_1_output.html", null ],
    [ "Amuse::RPI::OutputViewData", "d2/dd1/struct_amuse_1_1_r_p_i_1_1_output_view_data.html", null ],
    [ "Amuse::RPI::FGData::Pass", "d1/da3/struct_amuse_1_1_r_p_i_1_1_f_g_data_1_1_pass.html", null ],
    [ "Amuse::Core::Path", "df/db9/class_amuse_1_1_core_1_1_path.html", null ],
    [ "Amuse::Core::Periodic", "da/d51/class_amuse_1_1_core_1_1_periodic.html", null ],
    [ "Amuse::Core::Pimpl&lt; T &gt;", "d4/d30/class_amuse_1_1_core_1_1_pimpl.html", null ],
    [ "Amuse::RHI::PipelineStateDesc", "de/d3f/struct_amuse_1_1_r_h_i_1_1_pipeline_state_desc.html", null ],
    [ "Amuse::Core::Plane", "de/ddb/struct_amuse_1_1_core_1_1_plane.html", null ],
    [ "Amuse::Core::Point", "d9/d4b/struct_amuse_1_1_core_1_1_point.html", null ],
    [ "Amuse::RPI::PointLightData", "d5/dac/struct_amuse_1_1_r_p_i_1_1_point_light_data.html", null ],
    [ "Amuse::Core::Property", "d7/d3a/class_amuse_1_1_core_1_1_property.html", null ],
    [ "Amuse::Core::EventNotifier&lt; Args &gt;::Proxy", "d7/d60/class_amuse_1_1_core_1_1_event_notifier_1_1_proxy.html", null ],
    [ "Amuse::Core::Quat", "d3/da5/struct_amuse_1_1_core_1_1_quat.html", null ],
    [ "Amuse::Core::Random", "d3/dca/class_amuse_1_1_core_1_1_random.html", null ],
    [ "Amuse::Core::Range", "d5/d54/struct_amuse_1_1_core_1_1_range.html", null ],
    [ "Amuse::RHI::RasterizerDesc", "d7/dac/struct_amuse_1_1_r_h_i_1_1_rasterizer_desc.html", null ],
    [ "Amuse::Core::Rect", "d8/d17/struct_amuse_1_1_core_1_1_rect.html", null ],
    [ "Amuse::Core::Ref&lt; T &gt;", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::ReflectionFunction", "d1/d4b/struct_amuse_1_1_core_1_1_reflection_function.html", null ],
    [ "Amuse::Core::RefObject", "d1/d85/class_amuse_1_1_core_1_1_ref_object.html", [
      [ "Amuse::Platform::Window", "dc/d63/class_amuse_1_1_platform_1_1_window.html", null ],
      [ "Amuse::RHI::GraphicFileEvent", "dc/de0/class_amuse_1_1_r_h_i_1_1_graphic_file_event.html", null ],
      [ "Amuse::RHI::GraphicFileHandle", "da/db5/class_amuse_1_1_r_h_i_1_1_graphic_file_handle.html", null ],
      [ "Amuse::RHI::GraphicFileQueue", "d8/d50/class_amuse_1_1_r_h_i_1_1_graphic_file_queue.html", null ],
      [ "Amuse::RHI::GraphicObject", "d2/d2f/class_amuse_1_1_r_h_i_1_1_graphic_object.html", [
        [ "Amuse::RHI::Buffer", "d7/d8d/class_amuse_1_1_r_h_i_1_1_buffer.html", null ],
        [ "Amuse::RHI::CommandList", "d7/dc8/class_amuse_1_1_r_h_i_1_1_command_list.html", null ],
        [ "Amuse::RHI::ComputePipelineState", "d9/dab/class_amuse_1_1_r_h_i_1_1_compute_pipeline_state.html", null ],
        [ "Amuse::RHI::DescriptorLayout", "dc/db6/class_amuse_1_1_r_h_i_1_1_descriptor_layout.html", null ],
        [ "Amuse::RHI::DescriptorTable", "d2/d8f/class_amuse_1_1_r_h_i_1_1_descriptor_table.html", null ],
        [ "Amuse::RHI::EventQuery", "d4/d3a/class_amuse_1_1_r_h_i_1_1_event_query.html", null ],
        [ "Amuse::RHI::Fence", "d9/d03/class_amuse_1_1_r_h_i_1_1_fence.html", null ],
        [ "Amuse::RHI::PipelineState", "d6/d59/class_amuse_1_1_r_h_i_1_1_pipeline_state.html", null ],
        [ "Amuse::RHI::RootSignature", "de/d11/class_amuse_1_1_r_h_i_1_1_root_signature.html", null ],
        [ "Amuse::RHI::Sampler", "da/d9b/class_amuse_1_1_r_h_i_1_1_sampler.html", null ],
        [ "Amuse::RHI::Shader", "d7/d68/class_amuse_1_1_r_h_i_1_1_shader.html", null ],
        [ "Amuse::RHI::SwapChain", "d5/df6/class_amuse_1_1_r_h_i_1_1_swap_chain.html", null ],
        [ "Amuse::RHI::Texture", "de/d60/class_amuse_1_1_r_h_i_1_1_texture.html", [
          [ "Amuse::RHI::RenderTexture", "da/d86/class_amuse_1_1_r_h_i_1_1_render_texture.html", null ]
        ] ],
        [ "Amuse::RHI::TimerQuery", "d4/d23/class_amuse_1_1_r_h_i_1_1_timer_query.html", null ],
        [ "Amuse::RHI::VertexLayout", "dc/df3/class_amuse_1_1_r_h_i_1_1_vertex_layout.html", null ]
      ] ],
      [ "Amuse::RPI::Material", "db/dd4/class_amuse_1_1_r_p_i_1_1_material.html", null ],
      [ "Amuse::RPI::MaterialShader", "d6/db9/class_amuse_1_1_r_p_i_1_1_material_shader.html", null ],
      [ "Amuse::RPI::Mesh", "da/d90/class_amuse_1_1_r_p_i_1_1_mesh.html", null ],
      [ "Amuse::RPI::RenderPipeline", "db/d59/class_amuse_1_1_r_p_i_1_1_render_pipeline.html", [
        [ "Amuse::RPI::ImGuiRenderPipeline", "d6/d0d/class_amuse_1_1_r_p_i_1_1_im_gui_render_pipeline.html", null ],
        [ "Amuse::RPI::UniversalRenderPipeline", "d5/da5/class_amuse_1_1_r_p_i_1_1_universal_render_pipeline.html", null ]
      ] ]
    ] ],
    [ "Amuse::RPI::RenderFeature", "d6/d16/class_amuse_1_1_r_p_i_1_1_render_feature.html", [
      [ "Amuse::RPI::CameraRenderFeature", "d3/d30/class_amuse_1_1_r_p_i_1_1_camera_render_feature.html", null ],
      [ "Amuse::RPI::ImGuiRenderFeature", "d4/db4/class_amuse_1_1_r_p_i_1_1_im_gui_render_feature.html", null ],
      [ "Amuse::RPI::MaterialRenderFeature", "d2/d26/class_amuse_1_1_r_p_i_1_1_material_render_feature.html", null ],
      [ "Amuse::RPI::MeshRenderFeature", "dc/dc6/class_amuse_1_1_r_p_i_1_1_mesh_render_feature.html", null ],
      [ "Amuse::RPI::PointLightRenderFeature", "d2/d7b/class_amuse_1_1_r_p_i_1_1_point_light_render_feature.html", null ]
    ] ],
    [ "Amuse::RPI::RenderFeatureSet", "dc/d12/class_amuse_1_1_r_p_i_1_1_render_feature_set.html", null ],
    [ "Amuse::RPI::RenderPass", "dd/d64/class_amuse_1_1_r_p_i_1_1_render_pass.html", [
      [ "Amuse::RPI::DeferredPass", "d6/d6f/class_amuse_1_1_r_p_i_1_1_deferred_pass.html", null ],
      [ "Amuse::RPI::EarlyZPass", "da/db3/class_amuse_1_1_r_p_i_1_1_early_z_pass.html", null ],
      [ "Amuse::RPI::GBufferPass", "d0/db6/class_amuse_1_1_r_p_i_1_1_g_buffer_pass.html", null ],
      [ "Amuse::RPI::ImGuiPass", "d0/d3f/class_amuse_1_1_r_p_i_1_1_im_gui_pass.html", null ],
      [ "Amuse::RPI::MaskedPass", "d7/d8f/class_amuse_1_1_r_p_i_1_1_masked_pass.html", null ],
      [ "Amuse::RPI::OpaquePass", "d7/d3c/class_amuse_1_1_r_p_i_1_1_opaque_pass.html", null ],
      [ "Amuse::RPI::OutputPass", "d1/d12/class_amuse_1_1_r_p_i_1_1_output_pass.html", null ]
    ] ],
    [ "Amuse::RHI::RenderPassColorTargetDesc", "d7/dd4/struct_amuse_1_1_r_h_i_1_1_render_pass_color_target_desc.html", null ],
    [ "Amuse::RHI::RenderPassTargetDesc", "d7/d4d/struct_amuse_1_1_r_h_i_1_1_render_pass_target_desc.html", null ],
    [ "Amuse::RPI::RenderScene", "dd/dc7/class_amuse_1_1_r_p_i_1_1_render_scene.html", null ],
    [ "Amuse::RHI::RenderTextureDesc", "d4/dc2/struct_amuse_1_1_r_h_i_1_1_render_texture_desc.html", null ],
    [ "Amuse::RPI::RenderView", "d1/df2/class_amuse_1_1_r_p_i_1_1_render_view.html", null ],
    [ "Amuse::RPI::RenderViewData", "de/d3c/struct_amuse_1_1_r_p_i_1_1_render_view_data.html", null ],
    [ "Amuse::RPI::ResizableBuffer", "d7/da8/class_amuse_1_1_r_p_i_1_1_resizable_buffer.html", null ],
    [ "Amuse::RPI::FGData::Resource", "d9/da8/struct_amuse_1_1_r_p_i_1_1_f_g_data_1_1_resource.html", null ],
    [ "Amuse::RHI::RHIConfig", "d8/d50/struct_amuse_1_1_r_h_i_1_1_r_h_i_config.html", null ],
    [ "Amuse::RHI::RHIFeatures", "d7/dd6/struct_amuse_1_1_r_h_i_1_1_r_h_i_features.html", null ],
    [ "Amuse::RHI::RootConstantsDesc", "da/d4a/struct_amuse_1_1_r_h_i_1_1_root_constants_desc.html", null ],
    [ "Amuse::RHI::RootSignatureDesc", "dd/d50/struct_amuse_1_1_r_h_i_1_1_root_signature_desc.html", null ],
    [ "Amuse::Core::Rot", "da/d68/struct_amuse_1_1_core_1_1_rot.html", null ],
    [ "Amuse::RHI::SampleDesc", "dd/d46/struct_amuse_1_1_r_h_i_1_1_sample_desc.html", null ],
    [ "Amuse::RHI::SamplerDesc", "d9/d3d/struct_amuse_1_1_r_h_i_1_1_sampler_desc.html", null ],
    [ "Amuse::RHI::SamplerDescEqual", "d9/d32/struct_amuse_1_1_r_h_i_1_1_sampler_desc_equal.html", null ],
    [ "Amuse::RHI::SamplerDescHasher", "da/dda/struct_amuse_1_1_r_h_i_1_1_sampler_desc_hasher.html", null ],
    [ "Amuse::Core::Schedule&lt; Args &gt;", "da/d73/class_amuse_1_1_core_1_1_schedule.html", null ],
    [ "Amuse::Core::ScheduleBuildError", "d8/de7/struct_amuse_1_1_core_1_1_schedule_build_error.html", null ],
    [ "Amuse::Core::ScheduleBuildResult", "d0/d98/class_amuse_1_1_core_1_1_schedule_build_result.html", null ],
    [ "Amuse::Core::ScheduleBuildSettings", "d5/d45/struct_amuse_1_1_core_1_1_schedule_build_settings.html", null ],
    [ "Amuse::Core::ScheduleBuildWarning", "d9/dd4/struct_amuse_1_1_core_1_1_schedule_build_warning.html", null ],
    [ "Amuse::Core::ScheduleExecutor", "d0/d32/class_amuse_1_1_core_1_1_schedule_executor.html", null ],
    [ "Amuse::Core::ScheduleExecutorConfig", "de/d86/struct_amuse_1_1_core_1_1_schedule_executor_config.html", null ],
    [ "Amuse::Core::ScheduleSet", "dd/dff/class_amuse_1_1_core_1_1_schedule_set.html", null ],
    [ "ImGui::Amuse::ScopedContext", "de/d63/class_im_gui_1_1_amuse_1_1_scoped_context.html", null ],
    [ "ImGui::ScopedContext", "de/d63/class_im_gui_1_1_amuse_1_1_scoped_context.html", null ],
    [ "ImGui::Amuse::ScopedFont", "d6/d2f/class_im_gui_1_1_amuse_1_1_scoped_font.html", null ],
    [ "ImGui::ScopedFont", "d6/d2f/class_im_gui_1_1_amuse_1_1_scoped_font.html", null ],
    [ "ImGui::Amuse::ScopedGroup", "d9/d21/class_im_gui_1_1_amuse_1_1_scoped_group.html", null ],
    [ "ImGui::ScopedGroup", "d9/d21/class_im_gui_1_1_amuse_1_1_scoped_group.html", null ],
    [ "ImGui::Amuse::ScopedID", "d6/de9/class_im_gui_1_1_amuse_1_1_scoped_i_d.html", null ],
    [ "ImGui::ScopedID", "d6/de9/class_im_gui_1_1_amuse_1_1_scoped_i_d.html", null ],
    [ "ImGui::Amuse::ScopedIndent", "df/db3/class_im_gui_1_1_amuse_1_1_scoped_indent.html", null ],
    [ "ImGui::ScopedIndent", "df/db3/class_im_gui_1_1_amuse_1_1_scoped_indent.html", null ],
    [ "ImGui::Amuse::ScopedItemWidth", "da/db2/class_im_gui_1_1_amuse_1_1_scoped_item_width.html", null ],
    [ "ImGui::ScopedItemWidth", "da/db2/class_im_gui_1_1_amuse_1_1_scoped_item_width.html", null ],
    [ "ImGui::Amuse::ScopedStyleColor", "d0/de2/class_im_gui_1_1_amuse_1_1_scoped_style_color.html", [
      [ "ImGui::Amuse::ScopedButtonActiveColor", "d2/d6c/class_im_gui_1_1_amuse_1_1_scoped_button_active_color.html", null ],
      [ "ImGui::Amuse::ScopedButtonColor", "d1/d8c/class_im_gui_1_1_amuse_1_1_scoped_button_color.html", null ],
      [ "ImGui::Amuse::ScopedButtonHoveredColor", "d2/d4d/class_im_gui_1_1_amuse_1_1_scoped_button_hovered_color.html", null ],
      [ "ImGui::Amuse::ScopedTextColor", "d8/d51/class_im_gui_1_1_amuse_1_1_scoped_text_color.html", null ]
    ] ],
    [ "ImGui::ScopedStyleColor", "d0/de2/class_im_gui_1_1_amuse_1_1_scoped_style_color.html", [
      [ "ImGui::Amuse::ScopedButtonActiveColor", "d2/d6c/class_im_gui_1_1_amuse_1_1_scoped_button_active_color.html", null ],
      [ "ImGui::Amuse::ScopedButtonColor", "d1/d8c/class_im_gui_1_1_amuse_1_1_scoped_button_color.html", null ],
      [ "ImGui::Amuse::ScopedButtonHoveredColor", "d2/d4d/class_im_gui_1_1_amuse_1_1_scoped_button_hovered_color.html", null ],
      [ "ImGui::Amuse::ScopedTextColor", "d8/d51/class_im_gui_1_1_amuse_1_1_scoped_text_color.html", null ]
    ] ],
    [ "ImGui::Amuse::ScopedStyleVar", "d3/d02/class_im_gui_1_1_amuse_1_1_scoped_style_var.html", null ],
    [ "ImGui::ScopedStyleVar", "d3/d02/class_im_gui_1_1_amuse_1_1_scoped_style_var.html", null ],
    [ "ImGui::Amuse::ScopedStyleVec2Var", "d3/d64/class_im_gui_1_1_amuse_1_1_scoped_style_vec2_var.html", null ],
    [ "ImGui::ScopedStyleVec2Var", "d3/d64/class_im_gui_1_1_amuse_1_1_scoped_style_vec2_var.html", null ],
    [ "Amuse::Core::ScopeOutAction", "d3/d65/class_amuse_1_1_core_1_1_scope_out_action.html", null ],
    [ "Amuse::Core::ScopeValue&lt; T, V &gt;", "d3/da5/class_amuse_1_1_core_1_1_scope_value.html", null ],
    [ "Amuse::Core::Segment", "d1/de2/class_amuse_1_1_core_1_1_segment.html", null ],
    [ "Amuse::Core::ServiceBuilderBase", "d5/d79/class_amuse_1_1_core_1_1_service_builder_base.html", [
      [ "Amuse::Core::ServiceBuilder< T >", "d7/d66/class_amuse_1_1_core_1_1_service_builder.html", null ]
    ] ],
    [ "Amuse::Core::ServiceContainer", "d6/d84/class_amuse_1_1_core_1_1_service_container.html", null ],
    [ "Amuse::Core::ServiceInjector", "d6/d5f/class_amuse_1_1_core_1_1_service_injector.html", null ],
    [ "Amuse::RHI::SetDescriptorTableParam", "db/dbb/struct_amuse_1_1_r_h_i_1_1_set_descriptor_table_param.html", null ],
    [ "Amuse::RHI::SetRootConstantsParam", "d7/d56/struct_amuse_1_1_r_h_i_1_1_set_root_constants_param.html", null ],
    [ "Amuse::RHI::ShaderCompileDesc", "d9/d3f/struct_amuse_1_1_r_h_i_1_1_shader_compile_desc.html", null ],
    [ "Amuse::RPI::ShaderSet", "d0/d32/struct_amuse_1_1_r_p_i_1_1_shader_set.html", null ],
    [ "Amuse::Core::Singleton&lt; T &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", null ],
    [ "Amuse::Core::Singleton&lt; AsyncFileSystem &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::AsyncFileSystem", "d6/d37/class_amuse_1_1_core_1_1_async_file_system.html", null ]
    ] ],
    [ "Amuse::Core::Singleton&lt; Device &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::RHI::Device", "d1/d22/class_amuse_1_1_r_h_i_1_1_device.html", [
        [ "Amuse::RHI::DirectX12Device", "d9/d07/class_amuse_1_1_r_h_i_1_1_direct_x12_device.html", null ]
      ] ]
    ] ],
    [ "Amuse::Core::Singleton&lt; Graphics &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::RPI::Graphics", "d2/d38/class_amuse_1_1_r_p_i_1_1_graphics.html", null ]
    ] ],
    [ "Amuse::Core::Singleton&lt; InputModule &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Input::InputModule", "d6/d81/class_amuse_1_1_input_1_1_input_module.html", null ]
    ] ],
    [ "Amuse::Core::Singleton&lt; JobSystem &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::JobSystem", "da/d28/class_amuse_1_1_core_1_1_job_system.html", null ]
    ] ],
    [ "Amuse::Core::Singleton&lt; MaterialSystem &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::RPI::MaterialSystem", "d8/d1f/class_amuse_1_1_r_p_i_1_1_material_system.html", null ]
    ] ],
    [ "Amuse::Core::Singleton&lt; ThreadPool &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::ThreadPool", "dc/dbe/class_amuse_1_1_core_1_1_thread_pool.html", null ]
    ] ],
    [ "Amuse::Core::Singleton&lt; TypeInfoManager &gt;", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::TypeInfoManager", "da/d48/class_amuse_1_1_core_1_1_type_info_manager.html", null ]
    ] ],
    [ "Amuse::Core::Size", "de/d30/struct_amuse_1_1_core_1_1_size.html", null ],
    [ "Amuse::Core::SourceLocation", "d6/d94/struct_amuse_1_1_core_1_1_source_location.html", null ],
    [ "Amuse::Core::SpanAllocator", "de/dff/class_amuse_1_1_core_1_1_span_allocator.html", null ],
    [ "Amuse::RPI::SparseUploadBuffer&lt; T &gt;", "d4/dc4/class_amuse_1_1_r_p_i_1_1_sparse_upload_buffer.html", null ],
    [ "Amuse::Core::Sphere", "d0/de1/struct_amuse_1_1_core_1_1_sphere.html", null ],
    [ "Amuse::Core::Spline", "d3/de7/class_amuse_1_1_core_1_1_spline.html", null ],
    [ "Amuse::Core::Spline2D", "db/d6b/class_amuse_1_1_core_1_1_spline2_d.html", null ],
    [ "Amuse::RPI::SpotLightData", "d1/d75/struct_amuse_1_1_r_p_i_1_1_spot_light_data.html", null ],
    [ "Amuse::Core::StackTrace", "da/d85/struct_amuse_1_1_core_1_1_stack_trace.html", null ],
    [ "Amuse::Core::StackTraceElement", "da/dc0/struct_amuse_1_1_core_1_1_stack_trace_element.html", null ],
    [ "Amuse::RHI::StaticSamplerDesc", "d4/dc3/struct_amuse_1_1_r_h_i_1_1_static_sampler_desc.html", null ],
    [ "ImStb::STB_TexteditState", "d3/dbb/struct_im_stb_1_1_s_t_b___textedit_state.html", null ],
    [ "STB_TexteditState", "d4/d92/struct_s_t_b___textedit_state.html", null ],
    [ "stbrp_context", "d7/dc7/structstbrp__context.html", null ],
    [ "stbrp_node", "d0/dbb/structstbrp__node.html", null ],
    [ "stbrp_rect", "d5/d50/structstbrp__rect.html", null ],
    [ "ImStb::StbTexteditRow", "db/d21/struct_im_stb_1_1_stb_textedit_row.html", null ],
    [ "StbTexteditRow", "d1/d1e/struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "d6/d7d/structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "dd/d25/structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "d9/d0c/structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "d7/d70/structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "d1/d3f/structstbtt__fontinfo.html", null ],
    [ "stbtt_kerningentry", "dc/df5/structstbtt__kerningentry.html", null ],
    [ "stbtt_pack_context", "d6/dc9/structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "d9/d46/structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "d2/d0c/structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "d4/d8d/structstbtt__vertex.html", null ],
    [ "ImStb::StbUndoRecord", "d5/d7c/struct_im_stb_1_1_stb_undo_record.html", null ],
    [ "StbUndoRecord", "d8/d4a/struct_stb_undo_record.html", null ],
    [ "ImStb::StbUndoState", "d7/da9/struct_im_stb_1_1_stb_undo_state.html", null ],
    [ "StbUndoState", "dd/dfa/struct_stb_undo_state.html", null ],
    [ "STLAllocatorBase", null, [
      [ "Amuse::Core::STLAllocator< T >", "d8/d54/struct_amuse_1_1_core_1_1_s_t_l_allocator.html", null ]
    ] ],
    [ "Amuse::Core::Stream", "df/dc8/class_amuse_1_1_core_1_1_stream.html", [
      [ "Amuse::Core::BinaryStream", "d6/d31/class_amuse_1_1_core_1_1_binary_stream.html", null ],
      [ "Amuse::Core::File", "da/d8e/class_amuse_1_1_core_1_1_file.html", null ]
    ] ],
    [ "Amuse::Core::StringBase&lt; TChar &gt;", "da/d7a/class_amuse_1_1_core_1_1_string_base.html", null ],
    [ "Amuse::Core::StringEncoder", "dc/d28/class_amuse_1_1_core_1_1_string_encoder.html", null ],
    [ "Amuse::Core::StringSplitView", "d3/d99/class_amuse_1_1_core_1_1_string_split_view.html", [
      [ "Amuse::Core::CommaSplitView", "d6/d6a/class_amuse_1_1_core_1_1_comma_split_view.html", null ],
      [ "Amuse::Core::LineBreakSplitView", "dc/d20/class_amuse_1_1_core_1_1_line_break_split_view.html", null ],
      [ "Amuse::Core::TabSplitView", "d4/d55/class_amuse_1_1_core_1_1_tab_split_view.html", null ]
    ] ],
    [ "Amuse::Core::StringViewBase&lt; TChar &gt;", "d1/dcf/class_amuse_1_1_core_1_1_string_view_base.html", null ],
    [ "Amuse::RHI::SwapChainDesc", "d6/d44/struct_amuse_1_1_r_h_i_1_1_swap_chain_desc.html", null ],
    [ "Amuse::Core::Swapper&lt; T &gt;", "de/dfa/class_amuse_1_1_core_1_1_swapper.html", null ],
    [ "Amuse::Core::SyncHandleManager&lt; T, Deleter &gt;", "d7/d21/class_amuse_1_1_core_1_1_sync_handle_manager.html", null ],
    [ "Amuse::RHI::SystemDesc", "da/da9/struct_amuse_1_1_r_h_i_1_1_system_desc.html", null ],
    [ "Amuse::Core::TagBuilder", "d5/d17/class_amuse_1_1_core_1_1_tag_builder.html", [
      [ "Amuse::Core::ClassBuilder", "d0/d95/class_amuse_1_1_core_1_1_class_builder.html", [
        [ "Amuse::Core::ClassBuilderTemplate< _T >", "da/d8a/class_amuse_1_1_core_1_1_class_builder_template.html", null ]
      ] ],
      [ "Amuse::Core::EnumBuilder", "d8/ddd/class_amuse_1_1_core_1_1_enum_builder.html", [
        [ "Amuse::Core::EnumBuilderTemplate< _T >", "d1/dcb/class_amuse_1_1_core_1_1_enum_builder_template.html", null ]
      ] ],
      [ "Amuse::Core::PrimitiveBuilder", "d7/d60/class_amuse_1_1_core_1_1_primitive_builder.html", [
        [ "Amuse::Core::PrimitiveBuilderTemplate< _T >", "db/d67/class_amuse_1_1_core_1_1_primitive_builder_template.html", null ]
      ] ]
    ] ],
    [ "Amuse::Core::TagInfo", "da/d3a/struct_amuse_1_1_core_1_1_tag_info.html", [
      [ "Amuse::Core::ConstructorInfo", "d6/d8e/struct_amuse_1_1_core_1_1_constructor_info.html", null ],
      [ "Amuse::Core::EnumElementInfo", "d2/de7/struct_amuse_1_1_core_1_1_enum_element_info.html", null ],
      [ "Amuse::Core::MethodInfo", "d5/d20/struct_amuse_1_1_core_1_1_method_info.html", null ],
      [ "Amuse::Core::PropertyInfo", "d7/dd1/struct_amuse_1_1_core_1_1_property_info.html", null ],
      [ "Amuse::Core::TypeInfo", "d3/d31/struct_amuse_1_1_core_1_1_type_info.html", null ]
    ] ],
    [ "Amuse::Core::Task", "db/d92/class_amuse_1_1_core_1_1_task.html", null ],
    [ "Amuse::Core::TaskGroup", "de/d28/class_amuse_1_1_core_1_1_task_group.html", null ],
    [ "Amuse::Core::TCPClient", "da/dce/class_amuse_1_1_core_1_1_t_c_p_client.html", null ],
    [ "Amuse::Core::TCPServer", "d1/d28/class_amuse_1_1_core_1_1_t_c_p_server.html", null ],
    [ "Amuse::Platform::TextInput", "dc/d36/class_amuse_1_1_platform_1_1_text_input.html", null ],
    [ "Amuse::RHI::TextureBarrier", "dc/d9f/struct_amuse_1_1_r_h_i_1_1_texture_barrier.html", null ],
    [ "Amuse::RHI::TextureCopyRegion", "db/dce/struct_amuse_1_1_r_h_i_1_1_texture_copy_region.html", null ],
    [ "Amuse::RHI::GraphicFileRequest::TextureDesc", "d3/d65/struct_amuse_1_1_r_h_i_1_1_graphic_file_request_1_1_texture_desc.html", null ],
    [ "Amuse::RHI::TextureDesc", "df/d82/struct_amuse_1_1_r_h_i_1_1_texture_desc.html", null ],
    [ "Amuse::RHI::TextureFormatUtility", "d7/d71/class_amuse_1_1_r_h_i_1_1_texture_format_utility.html", null ],
    [ "Amuse::RHI::GraphicFileRequest::TextureSequenceDesc", "df/d0a/struct_amuse_1_1_r_h_i_1_1_graphic_file_request_1_1_texture_sequence_desc.html", null ],
    [ "Amuse::RHI::TextureSubresource", "d2/db4/struct_amuse_1_1_r_h_i_1_1_texture_subresource.html", null ],
    [ "Amuse::RHI::TextureSubresourceRange", "d3/df1/struct_amuse_1_1_r_h_i_1_1_texture_subresource_range.html", null ],
    [ "Amuse::RHI::TextureViewDesc", "d5/d16/struct_amuse_1_1_r_h_i_1_1_texture_view_desc.html", null ],
    [ "Amuse::Core::ThreadDesc", "de/dbb/struct_amuse_1_1_core_1_1_thread_desc.html", null ],
    [ "Amuse::Core::TimeSpan", "db/df5/class_amuse_1_1_core_1_1_time_span.html", null ],
    [ "Amuse::Core::TLSFBlock", "d4/d6a/struct_amuse_1_1_core_1_1_t_l_s_f_block.html", null ],
    [ "Amuse::Core::Transform", "d0/d24/class_amuse_1_1_core_1_1_transform.html", null ],
    [ "Amuse::Core::Transition", "d4/d1b/class_amuse_1_1_core_1_1_transition.html", null ],
    [ "Amuse::Core::Triangle", "d9/ddf/class_amuse_1_1_core_1_1_triangle.html", null ],
    [ "std::true_type", null, [
      [ "Amuse::Core::is_map< HashMap< TKey, TValue > >", "dc/d63/struct_amuse_1_1_core_1_1is__map_3_01_hash_map_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
      [ "Amuse::Core::is_map< Map< TKey, TValue > >", "d8/da4/struct_amuse_1_1_core_1_1is__map_3_01_map_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< Array< T, N > >", "d4/d8c/struct_amuse_1_1_core_1_1is__sequence_3_01_array_3_01_t_00_01_n_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< HashSet< T, ALLOCATOR > >", "dd/d3c/struct_amuse_1_1_core_1_1is__sequence_3_01_hash_set_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< List< T, ALLOCATOR > >", "d6/d92/struct_amuse_1_1_core_1_1is__sequence_3_01_list_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< Set< T, ALLOCATOR > >", "d1/dfc/struct_amuse_1_1_core_1_1is__sequence_3_01_set_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< T[N]>", "d6/d8f/struct_amuse_1_1_core_1_1is__sequence_3_01_t_0f_n_0e_4.html", null ],
      [ "Amuse::Core::is_sequence< Vector< T, ALLOCATOR > >", "da/d1b/struct_amuse_1_1_core_1_1is__sequence_3_01_vector_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ]
    ] ],
    [ "Amuse::Core::Type", "dd/db0/class_amuse_1_1_core_1_1_type.html", null ],
    [ "Amuse::Core::TypedPointer", "d7/dd5/class_amuse_1_1_core_1_1_typed_pointer.html", null ],
    [ "Amuse::Core::TypeRegister", "d6/d66/struct_amuse_1_1_core_1_1_type_register.html", null ],
    [ "Amuse::Core::TypeRegisterTemplate&lt; T &gt;", "d3/d48/struct_amuse_1_1_core_1_1_type_register_template.html", null ],
    [ "Amuse::RPI::MeshRenderFeature::MeshViewData::CPUData::Unit", "d8/d75/struct_amuse_1_1_r_p_i_1_1_mesh_render_feature_1_1_mesh_view_data_1_1_c_p_u_data_1_1_unit.html", null ],
    [ "Amuse::RPI::MeshRenderFeature::UpdateContext", "df/d02/struct_amuse_1_1_r_p_i_1_1_mesh_render_feature_1_1_update_context.html", null ],
    [ "Amuse::Core::UUID", "d0/d96/struct_amuse_1_1_core_1_1_u_u_i_d.html", null ],
    [ "Amuse::Core::Vec2", "df/d62/struct_amuse_1_1_core_1_1_vec2.html", null ],
    [ "Amuse::Core::Vec3", "d7/d02/struct_amuse_1_1_core_1_1_vec3.html", null ],
    [ "Amuse::Core::Vec4", "da/da9/struct_amuse_1_1_core_1_1_vec4.html", null ],
    [ "Amuse::RHI::VertexAttribute", "db/df6/struct_amuse_1_1_r_h_i_1_1_vertex_attribute.html", null ],
    [ "Amuse::RHI::VertexLayoutDesc", "dc/dd6/struct_amuse_1_1_r_h_i_1_1_vertex_layout_desc.html", null ],
    [ "Amuse::RHI::VideoCard", "dd/d49/struct_amuse_1_1_r_h_i_1_1_video_card.html", null ],
    [ "Amuse::RHI::VideoOutput", "df/db9/struct_amuse_1_1_r_h_i_1_1_video_output.html", null ],
    [ "Amuse::RHI::VideoOutputMode", "dd/de9/struct_amuse_1_1_r_h_i_1_1_video_output_mode.html", null ],
    [ "Amuse::Core::Viewport", "d0/d65/struct_amuse_1_1_core_1_1_viewport.html", null ],
    [ "Amuse::RHI::VulkanRHIConfig", "d4/d78/struct_amuse_1_1_r_h_i_1_1_vulkan_r_h_i_config.html", null ],
    [ "Amuse::Platform::WindowDesc", "d9/d54/struct_amuse_1_1_platform_1_1_window_desc.html", null ],
    [ "Amuse::Platform::WindowEventArgs", "de/dfb/struct_amuse_1_1_platform_1_1_window_event_args.html", null ],
    [ "Amuse::Core::XmlNode", "d9/d2d/class_amuse_1_1_core_1_1_xml_node.html", [
      [ "Amuse::Core::Xml", "dd/d97/class_amuse_1_1_core_1_1_xml.html", null ]
    ] ],
    [ "Amuse::Core::YesNo&lt; Tag &gt;", "d1/d0c/class_amuse_1_1_core_1_1_yes_no.html", null ]
];