var hierarchy =
[
    [ "Amuse::Core::AABB", "d0/d8d/struct_amuse_1_1_core_1_1_a_a_b_b.html", null ],
    [ "Amuse::Core::Allocator", "da/dba/class_amuse_1_1_core_1_1_allocator.html", null ],
    [ "Amuse::Core::Any", "d3/d9a/class_amuse_1_1_core_1_1_any.html", null ],
    [ "Amuse::Core::ArgumentInfo", "d7/dbc/struct_amuse_1_1_core_1_1_argument_info.html", null ],
    [ "Amuse::Platform::Arguments", "d5/d31/class_amuse_1_1_platform_1_1_arguments.html", null ],
    [ "Amuse::Core::AsyncFile", "d3/dd2/class_amuse_1_1_core_1_1_async_file.html", null ],
    [ "Amuse::Core::AsyncFileEvent", "d3/d41/class_amuse_1_1_core_1_1_async_file_event.html", null ],
    [ "Amuse::Core::AsyncFileHandle", "d3/d43/class_amuse_1_1_core_1_1_async_file_handle.html", null ],
    [ "Amuse::Core::AsyncFileQueue", "d8/da8/class_amuse_1_1_core_1_1_async_file_queue.html", null ],
    [ "Amuse::Core::AsyncFileRequest", "dd/dae/struct_amuse_1_1_core_1_1_async_file_request.html", null ],
    [ "Amuse::Input::Axis", "d8/d4e/class_amuse_1_1_input_1_1_axis.html", null ],
    [ "Amuse::RHI::BeginPassParam", "d5/d8d/struct_amuse_1_1_r_h_i_1_1_begin_pass_param.html", null ],
    [ "Amuse::Core::BinaryReader", "d5/d77/class_amuse_1_1_core_1_1_binary_reader.html", null ],
    [ "Amuse::Core::BinaryWriter", "d2/d17/class_amuse_1_1_core_1_1_binary_writer.html", null ],
    [ "Amuse::RHI::Binding", "d5/d13/struct_amuse_1_1_r_h_i_1_1_binding.html", null ],
    [ "Amuse::RHI::BindingItem", "d7/d74/struct_amuse_1_1_r_h_i_1_1_binding_item.html", null ],
    [ "Amuse::RHI::BindlessHandle", "d4/d5b/struct_amuse_1_1_r_h_i_1_1_bindless_handle.html", null ],
    [ "Amuse::Core::BitFlags< TEnum, TBitsType >", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::BitFlags< BufferFlag >", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::BitFlags< ColorComponent >", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::BitFlags< RenderPassFlag >", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::BitFlags< RootSignatureFlag >", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::BitFlags< TextureFlag >", "d8/d40/class_amuse_1_1_core_1_1_bit_flags.html", null ],
    [ "Amuse::Core::Bitmap", "d6/d91/class_amuse_1_1_core_1_1_bitmap.html", null ],
    [ "Amuse::Core::BitOp", "dc/df9/struct_amuse_1_1_core_1_1_bit_op.html", null ],
    [ "Amuse::RHI::BlendDesc", "d2/df6/struct_amuse_1_1_r_h_i_1_1_blend_desc.html", null ],
    [ "Amuse::Core::Blob", "df/d96/class_amuse_1_1_core_1_1_blob.html", null ],
    [ "Amuse::Core::BlobView", "d6/d80/class_amuse_1_1_core_1_1_blob_view.html", null ],
    [ "Amuse::Core::Bounds", "d3/d82/struct_amuse_1_1_core_1_1_bounds.html", null ],
    [ "Amuse::Core::Box", "d4/d7d/struct_amuse_1_1_core_1_1_box.html", null ],
    [ "Amuse::RHI::BufferBarrier", "d0/d0b/struct_amuse_1_1_r_h_i_1_1_buffer_barrier.html", null ],
    [ "Amuse::RHI::BufferCopyRegion", "d0/d8e/struct_amuse_1_1_r_h_i_1_1_buffer_copy_region.html", null ],
    [ "Amuse::RHI::BufferDesc", "d7/dab/struct_amuse_1_1_r_h_i_1_1_buffer_desc.html", null ],
    [ "Amuse::RHI::GraphicFileRequest::BufferDesc", "de/d62/struct_amuse_1_1_r_h_i_1_1_graphic_file_request_1_1_buffer_desc.html", null ],
    [ "Amuse::RHI::BufferTextureCopyRegion", "dd/d41/struct_amuse_1_1_r_h_i_1_1_buffer_texture_copy_region.html", null ],
    [ "Amuse::RHI::BufferViewDesc", "d7/d1b/struct_amuse_1_1_r_h_i_1_1_buffer_view_desc.html", null ],
    [ "Amuse::Input::Button", "db/dab/class_amuse_1_1_input_1_1_button.html", null ],
    [ "Amuse::Core::Capsule", "d9/da8/struct_amuse_1_1_core_1_1_capsule.html", null ],
    [ "Amuse::Core::Circle", "db/d9f/struct_amuse_1_1_core_1_1_circle.html", null ],
    [ "Amuse::Core::ClassTrait< T >", "de/d38/class_amuse_1_1_core_1_1_class_trait.html", null ],
    [ "Amuse::RHI::ClearColor", "dc/d68/struct_amuse_1_1_r_h_i_1_1_clear_color.html", null ],
    [ "Amuse::Core::Color", "d9/de4/struct_amuse_1_1_core_1_1_color.html", null ],
    [ "Amuse::RHI::CommandListDesc", "d8/d93/struct_amuse_1_1_r_h_i_1_1_command_list_desc.html", null ],
    [ "Amuse::Core::ComponentHolder< T >", "d5/df2/class_amuse_1_1_core_1_1_component_holder.html", null ],
    [ "Amuse::Core::ComponentManager< T >", "d8/d02/class_amuse_1_1_core_1_1_component_manager.html", null ],
    [ "Amuse::Core::Compression", "de/de3/class_amuse_1_1_core_1_1_compression.html", null ],
    [ "Amuse::RHI::ComputePipelineStateDesc", "d2/dbc/struct_amuse_1_1_r_h_i_1_1_compute_pipeline_state_desc.html", null ],
    [ "Amuse::Core::HandleForwardList< T >::const_iterator", "d4/d7f/class_amuse_1_1_core_1_1_handle_forward_list_1_1const__iterator.html", [
      [ "Amuse::Core::HandleForwardList< T >::iterator", "d0/dce/class_amuse_1_1_core_1_1_handle_forward_list_1_1iterator.html", null ]
    ] ],
    [ "Amuse::Core::HandleList< T >::const_iterator", "d3/de2/class_amuse_1_1_core_1_1_handle_list_1_1const__iterator.html", [
      [ "Amuse::Core::HandleList< T >::iterator", "d4/d5c/class_amuse_1_1_core_1_1_handle_list_1_1iterator.html", null ]
    ] ],
    [ "Amuse::Core::ConstValue< T, N >", "df/d46/struct_amuse_1_1_core_1_1_const_value.html", null ],
    [ "Amuse::RHI::CopyTextureParam", "d4/dc4/struct_amuse_1_1_r_h_i_1_1_copy_texture_param.html", null ],
    [ "Amuse::Core::CRCHash", "d6/d57/class_amuse_1_1_core_1_1_c_r_c_hash.html", null ],
    [ "Amuse::Core::Cylinder", "dc/d5d/struct_amuse_1_1_core_1_1_cylinder.html", null ],
    [ "Amuse::Core::DateTime", "df/def/struct_amuse_1_1_core_1_1_date_time.html", null ],
    [ "Amuse::Core::Delegate< R(Args...), BufferSize >", "d6/d24/class_amuse_1_1_core_1_1_delegate_3_01_r_07_args_8_8_8_08_00_01_buffer_size_01_4.html", null ],
    [ "Amuse::RHI::DepthStencilDesc", "db/d85/struct_amuse_1_1_r_h_i_1_1_depth_stencil_desc.html", null ],
    [ "Amuse::RHI::DescriptorLayoutDesc", "d5/d72/struct_amuse_1_1_r_h_i_1_1_descriptor_layout_desc.html", null ],
    [ "Amuse::RHI::DescriptorTableDesc", "d4/df3/struct_amuse_1_1_r_h_i_1_1_descriptor_table_desc.html", null ],
    [ "Amuse::RHI::DeviceAdapterInfo", "d9/d41/struct_amuse_1_1_r_h_i_1_1_device_adapter_info.html", null ],
    [ "Amuse::Input::DirectInput", "df/dba/class_amuse_1_1_input_1_1_direct_input.html", null ],
    [ "Amuse::Core::Directory", "d8/d6b/class_amuse_1_1_core_1_1_directory.html", null ],
    [ "Amuse::RHI::DirectX12RHIConfig", "da/dbf/struct_amuse_1_1_r_h_i_1_1_direct_x12_r_h_i_config.html", null ],
    [ "Amuse::RHI::DispatchParam", "d4/d76/struct_amuse_1_1_r_h_i_1_1_dispatch_param.html", null ],
    [ "Amuse::Platform::DLL", "d7/d41/class_amuse_1_1_platform_1_1_d_l_l.html", null ],
    [ "Amuse::RHI::DrawIndexedParam", "d4/dc3/struct_amuse_1_1_r_h_i_1_1_draw_indexed_param.html", null ],
    [ "Amuse::RHI::DrawParam", "d7/d99/struct_amuse_1_1_r_h_i_1_1_draw_param.html", null ],
    [ "Amuse::Core::Easing", "d0/da0/class_amuse_1_1_core_1_1_easing.html", null ],
    [ "Amuse::Core::Endian", "db/d2a/class_amuse_1_1_core_1_1_endian.html", null ],
    [ "Amuse::Core::ErrorCode", "d2/d73/class_amuse_1_1_core_1_1_error_code.html", null ],
    [ "std::exception", null, [
      [ "Amuse::Core::Exception", "d7/de5/class_amuse_1_1_core_1_1_exception.html", [
        [ "Amuse::Core::ArgumentException", "df/d88/class_amuse_1_1_core_1_1_argument_exception.html", null ],
        [ "Amuse::Core::ArithmeticException", "d8/d20/class_amuse_1_1_core_1_1_arithmetic_exception.html", null ],
        [ "Amuse::Core::FormatException", "d2/de8/class_amuse_1_1_core_1_1_format_exception.html", null ],
        [ "Amuse::Core::InvalidOperationException", "de/dd8/class_amuse_1_1_core_1_1_invalid_operation_exception.html", null ],
        [ "Amuse::Core::KeyNotFoundException", "d9/d80/class_amuse_1_1_core_1_1_key_not_found_exception.html", null ],
        [ "Amuse::Core::NotImplementedException", "d8/dcb/class_amuse_1_1_core_1_1_not_implemented_exception.html", null ],
        [ "Amuse::Core::NotSupportedException", "d9/dc4/class_amuse_1_1_core_1_1_not_supported_exception.html", null ],
        [ "Amuse::Core::OutOfRangeException", "df/dde/class_amuse_1_1_core_1_1_out_of_range_exception.html", null ],
        [ "Amuse::Core::PathNotFoundException", "d7/d5f/class_amuse_1_1_core_1_1_path_not_found_exception.html", null ],
        [ "Amuse::Core::XmlException", "da/d0a/class_amuse_1_1_core_1_1_xml_exception.html", null ]
      ] ]
    ] ],
    [ "std::false_type", null, [
      [ "Amuse::Core::is_iterator< class, class >", "d8/d3d/struct_amuse_1_1_core_1_1is__iterator.html", null ],
      [ "Amuse::Core::is_map< T >", "d2/d16/struct_amuse_1_1_core_1_1is__map.html", null ],
      [ "Amuse::Core::is_sequence< T >", "d3/dfb/struct_amuse_1_1_core_1_1is__sequence.html", null ]
    ] ],
    [ "Amuse::RHI::FenceDesc", "dd/ded/struct_amuse_1_1_r_h_i_1_1_fence_desc.html", null ],
    [ "Amuse::Core::FixedFunc< R(Args...), BufferSize >", "d4/db1/class_amuse_1_1_core_1_1_fixed_func_3_01_r_07_args_8_8_8_08_00_01_buffer_size_01_4.html", null ],
    [ "Amuse::Core::FixedStringBase< TChar, N >", "d4/ddd/class_amuse_1_1_core_1_1_fixed_string_base.html", null ],
    [ "Amuse::Core::FixedVector< T, N >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FixedVector< RenderPassTargetDesc, RENDER_TARGET_MAX >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FixedVector< StaticSamplerDesc, STATIC_SAMPLER_MAX >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FixedVector< std::stacktrace_entry, MAX_ENTRY_COUNT >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FixedVector< TextureFormat, RENDER_TARGET_MAX >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FixedVector< u8, 8 >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FixedVector< VertexAttribute, VERTEX_ATTRIBUTE_MAX >", "d3/dc2/class_amuse_1_1_core_1_1_fixed_vector.html", null ],
    [ "Amuse::Core::FloatCompression", "da/d8a/class_amuse_1_1_core_1_1_float_compression.html", null ],
    [ "Amuse::Core::Frustum", "db/d2e/struct_amuse_1_1_core_1_1_frustum.html", null ],
    [ "Amuse::Core::GDeflate", "d4/dbe/class_amuse_1_1_core_1_1_g_deflate.html", null ],
    [ "Amuse::Core::Global< T >", "d7/d77/class_amuse_1_1_core_1_1_global.html", null ],
    [ "Amuse::RHI::GraphicFile", "da/d89/class_amuse_1_1_r_h_i_1_1_graphic_file.html", null ],
    [ "Amuse::RHI::GraphicFileMipInfo", "d8/d14/struct_amuse_1_1_r_h_i_1_1_graphic_file_mip_info.html", null ],
    [ "Amuse::RHI::GraphicFileQueueDesc", "d2/dbf/struct_amuse_1_1_r_h_i_1_1_graphic_file_queue_desc.html", null ],
    [ "Amuse::RHI::GraphicFileRequest", "d7/dc9/struct_amuse_1_1_r_h_i_1_1_graphic_file_request.html", null ],
    [ "Amuse::Core::HalfLine", "db/d03/class_amuse_1_1_core_1_1_half_line.html", null ],
    [ "Amuse::Core::Handle< T, TNamespace >", "d3/d60/class_amuse_1_1_core_1_1_handle.html", null ],
    [ "Amuse::Core::HandleManager< T, Deleter >::Handle", "db/dbd/class_amuse_1_1_core_1_1_handle_manager_1_1_handle.html", null ],
    [ "HandleBase", null, [
      [ "Amuse::Core::HandleForwardList< T >::Handle", "dc/d57/class_amuse_1_1_core_1_1_handle_forward_list_1_1_handle.html", null ]
    ] ],
    [ "Amuse::Core::HandleManager< T, Deleter >", "da/d02/class_amuse_1_1_core_1_1_handle_manager.html", null ],
    [ "Amuse::Core::Hash", "d5/d6f/class_amuse_1_1_core_1_1_hash.html", null ],
    [ "Amuse::Core::SyncHandleManager< T, Deleter >::Hasher", "d0/df7/struct_amuse_1_1_core_1_1_sync_handle_manager_1_1_hasher.html", null ],
    [ "Amuse::Core::HSV", "d3/d4e/struct_amuse_1_1_core_1_1_h_s_v.html", null ],
    [ "Amuse::Input::IInputDevice", "dc/dcb/class_amuse_1_1_input_1_1_i_input_device.html", null ],
    [ "Amuse::Core::IndexedVector< T, TIndex, TDataVector, TIndexVector >", "db/d95/class_amuse_1_1_core_1_1_indexed_vector.html", null ],
    [ "Amuse::Core::IndexMap< TKey, TValue, THasher, TKeyEqual, TAllocator >", "d7/ddc/class_amuse_1_1_core_1_1_index_map.html", null ],
    [ "Amuse::RHI::IndirectCommandParam", "d9/d89/struct_amuse_1_1_r_h_i_1_1_indirect_command_param.html", null ],
    [ "Amuse::Core::INI", "df/d76/class_amuse_1_1_core_1_1_i_n_i.html", null ],
    [ "Amuse::Core::INISection", "d4/d97/class_amuse_1_1_core_1_1_i_n_i_section.html", null ],
    [ "Amuse::Input::InputConfig", "d0/d4b/struct_amuse_1_1_input_1_1_input_config.html", null ],
    [ "Amuse::Core::IntColor", "dc/d7f/struct_amuse_1_1_core_1_1_int_color.html", null ],
    [ "Amuse::Core::IntRect", "d9/dbf/struct_amuse_1_1_core_1_1_int_rect.html", null ],
    [ "Amuse::Core::IntrusiveQueue< T, pMember >", "d4/d06/class_amuse_1_1_core_1_1_intrusive_queue.html", null ],
    [ "Amuse::Core::IntrusiveQueue< Amuse::Core::HandleManager::Node, &Node::next >", "d4/d06/class_amuse_1_1_core_1_1_intrusive_queue.html", null ],
    [ "Amuse::Core::IntVec2", "d7/db0/struct_amuse_1_1_core_1_1_int_vec2.html", null ],
    [ "Amuse::Core::IntVec3", "df/db7/struct_amuse_1_1_core_1_1_int_vec3.html", null ],
    [ "Amuse::Core::IntVec4", "d8/dad/struct_amuse_1_1_core_1_1_int_vec4.html", null ],
    [ "Amuse::Core::IPAddress", "d0/da8/struct_amuse_1_1_core_1_1_i_p_address.html", null ],
    [ "Amuse::Core::StringSplitView::Iterator", "d3/df8/class_amuse_1_1_core_1_1_string_split_view_1_1_iterator.html", null ],
    [ "Amuse::Core::JobGroup", "d0/d57/class_amuse_1_1_core_1_1_job_group.html", null ],
    [ "Amuse::Input::Keyboard", "df/d41/class_amuse_1_1_input_1_1_keyboard.html", null ],
    [ "Amuse::Core::Line", "de/d82/struct_amuse_1_1_core_1_1_line.html", null ],
    [ "Amuse::Core::Locale", "db/d8d/class_amuse_1_1_core_1_1_locale.html", null ],
    [ "Amuse::Core::Log", "d3/dfd/struct_amuse_1_1_core_1_1_log.html", null ],
    [ "Amuse::Core::Logger", "d6/ded/class_amuse_1_1_core_1_1_logger.html", null ],
    [ "Amuse::Core::Margin", "d4/d7f/struct_amuse_1_1_core_1_1_margin.html", null ],
    [ "Amuse::Core::Math", "df/d2e/class_amuse_1_1_core_1_1_math.html", null ],
    [ "Amuse::Core::Matrix", "dc/d67/struct_amuse_1_1_core_1_1_matrix.html", null ],
    [ "Amuse::Core::MemorySize", "d5/d1f/struct_amuse_1_1_core_1_1_memory_size.html", null ],
    [ "Amuse::Core::MiniDelegate< R(Args...)>", "d2/d16/class_amuse_1_1_core_1_1_mini_delegate_3_01_r_07_args_8_8_8_08_4.html", null ],
    [ "Amuse::Input::Mouse", "dd/d1c/class_amuse_1_1_input_1_1_mouse.html", null ],
    [ "Amuse::Core::MTL", "dc/d59/class_amuse_1_1_core_1_1_m_t_l.html", null ],
    [ "Amuse::Core::Name", "d0/d53/class_amuse_1_1_core_1_1_name.html", null ],
    [ "Amuse::Core::Network", "d9/d11/class_amuse_1_1_core_1_1_network.html", null ],
    [ "Amuse::Core::HandleManager< T, Deleter >::Node", "d6/d5d/struct_amuse_1_1_core_1_1_handle_manager_1_1_node.html", null ],
    [ "Amuse::Core::Noise", "d4/d41/class_amuse_1_1_core_1_1_noise.html", null ],
    [ "Amuse::Core::Noncopyable", "dc/d43/class_amuse_1_1_core_1_1_noncopyable.html", [
      [ "Amuse::Core::EventNotifier< const Log & >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::HandleList< delegate_type >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 128, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 32, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< DirectX12BufferUploader >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< DirectX12TextureUploader >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< DirectX12DescriptorUploader >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::AnyContainer", "d3/daa/class_amuse_1_1_core_1_1_any_container.html", null ],
      [ "Amuse::Core::EventNotifier< Args >", "d3/d42/class_amuse_1_1_core_1_1_event_notifier.html", null ],
      [ "Amuse::Core::HandleForwardList< T >", "d3/ddf/class_amuse_1_1_core_1_1_handle_forward_list.html", null ],
      [ "Amuse::Core::HandleForwardList< T >::Handle", "dc/d57/class_amuse_1_1_core_1_1_handle_forward_list_1_1_handle.html", null ],
      [ "Amuse::Core::HandleList< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::HandleList< T >::Handle", "dd/d26/class_amuse_1_1_core_1_1_handle_list_1_1_handle.html", null ],
      [ "Amuse::Core::JobGroupHandle", "dc/d1f/class_amuse_1_1_core_1_1_job_group_handle.html", null ],
      [ "Amuse::Core::JobHandle", "da/d98/class_amuse_1_1_core_1_1_job_handle.html", null ],
      [ "Amuse::Core::MemoryStorageBase< T, SIZE, ALIGN >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::Mutex", "d5/d20/class_amuse_1_1_core_1_1_mutex.html", null ],
      [ "Amuse::Core::ScopeLock< TLockable >", "dd/df1/class_amuse_1_1_core_1_1_scope_lock.html", null ],
      [ "Amuse::Core::SpinLock", "d1/db6/class_amuse_1_1_core_1_1_spin_lock.html", null ],
      [ "Amuse::Core::TLSFMapper", "dc/d9f/class_amuse_1_1_core_1_1_t_l_s_f_mapper.html", null ],
      [ "Amuse::Core::Thread", "d4/dc8/class_amuse_1_1_core_1_1_thread.html", null ]
    ] ],
    [ "Amuse::Core::Nonmovable", "d6/d34/class_amuse_1_1_core_1_1_nonmovable.html", [
      [ "Amuse::Core::HandleList< delegate_type >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 128, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< Impl, 32, 8 >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< DirectX12BufferUploader >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< DirectX12TextureUploader >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::MemoryStorageBase< DirectX12DescriptorUploader >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::AnyContainer", "d3/daa/class_amuse_1_1_core_1_1_any_container.html", null ],
      [ "Amuse::Core::HandleForwardList< T >::Handle", "dc/d57/class_amuse_1_1_core_1_1_handle_forward_list_1_1_handle.html", null ],
      [ "Amuse::Core::HandleList< T >", "da/da9/class_amuse_1_1_core_1_1_handle_list.html", null ],
      [ "Amuse::Core::HandleList< T >::Handle", "dd/d26/class_amuse_1_1_core_1_1_handle_list_1_1_handle.html", null ],
      [ "Amuse::Core::JobGroupHandle", "dc/d1f/class_amuse_1_1_core_1_1_job_group_handle.html", null ],
      [ "Amuse::Core::JobHandle", "da/d98/class_amuse_1_1_core_1_1_job_handle.html", null ],
      [ "Amuse::Core::MemoryStorageBase< T, SIZE, ALIGN >", "d5/d6f/class_amuse_1_1_core_1_1_memory_storage_base.html", null ],
      [ "Amuse::Core::ThreadLocalContext< T >", "da/d56/class_amuse_1_1_core_1_1_thread_local_context.html", null ]
    ] ],
    [ "Amuse::Core::OBB", "d9/d95/struct_amuse_1_1_core_1_1_o_b_b.html", null ],
    [ "Amuse::Core::OBJ", "d4/d75/class_amuse_1_1_core_1_1_o_b_j.html", null ],
    [ "Amuse::Core::Path", "df/db9/class_amuse_1_1_core_1_1_path.html", null ],
    [ "Amuse::Core::Periodic", "da/d51/class_amuse_1_1_core_1_1_periodic.html", null ],
    [ "Amuse::Core::Pimpl< T >", "d4/d30/class_amuse_1_1_core_1_1_pimpl.html", null ],
    [ "Amuse::Core::Pimpl< class JobSystemImpl >", "d4/d30/class_amuse_1_1_core_1_1_pimpl.html", null ],
    [ "Amuse::Core::Pimpl< class MutexImpl >", "d4/d30/class_amuse_1_1_core_1_1_pimpl.html", null ],
    [ "Amuse::Core::Pimpl< class ThreadImpl >", "d4/d30/class_amuse_1_1_core_1_1_pimpl.html", null ],
    [ "Amuse::RHI::PipelineStateDesc", "de/d3f/struct_amuse_1_1_r_h_i_1_1_pipeline_state_desc.html", null ],
    [ "Amuse::Core::Plane", "de/ddb/struct_amuse_1_1_core_1_1_plane.html", null ],
    [ "Amuse::Core::Point", "d9/d4b/struct_amuse_1_1_core_1_1_point.html", null ],
    [ "Amuse::Core::Property", "d7/d3a/class_amuse_1_1_core_1_1_property.html", null ],
    [ "Amuse::Core::EventNotifier< Args >::Proxy", "d7/d60/class_amuse_1_1_core_1_1_event_notifier_1_1_proxy.html", null ],
    [ "Amuse::Core::Quat", "d3/da5/struct_amuse_1_1_core_1_1_quat.html", null ],
    [ "Amuse::Core::Random", "d3/dca/class_amuse_1_1_core_1_1_random.html", null ],
    [ "Amuse::Core::Range", "d5/d54/struct_amuse_1_1_core_1_1_range.html", null ],
    [ "Amuse::RHI::RasterizerDesc", "d7/dac/struct_amuse_1_1_r_h_i_1_1_rasterizer_desc.html", null ],
    [ "Amuse::Core::Rect", "d8/d17/struct_amuse_1_1_core_1_1_rect.html", null ],
    [ "Amuse::Core::Ref< T >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::Platform::Window >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::Buffer >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::CommandList >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::DescriptorLayout >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::DescriptorTable >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::GraphicFileHandle >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::RenderTexture >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::RootSignature >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::Shader >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::Texture >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::Ref< Amuse::RHI::VertexLayout >", "d8/d51/class_amuse_1_1_core_1_1_ref.html", null ],
    [ "Amuse::Core::ReflectionFunction", "d1/d4b/struct_amuse_1_1_core_1_1_reflection_function.html", null ],
    [ "Amuse::Core::RefObject", "d1/d85/class_amuse_1_1_core_1_1_ref_object.html", [
      [ "Amuse::Platform::Window", "dc/d63/class_amuse_1_1_platform_1_1_window.html", null ],
      [ "Amuse::RHI::GraphicFileEvent", "dc/de0/class_amuse_1_1_r_h_i_1_1_graphic_file_event.html", null ],
      [ "Amuse::RHI::GraphicFileHandle", "da/db5/class_amuse_1_1_r_h_i_1_1_graphic_file_handle.html", null ],
      [ "Amuse::RHI::GraphicFileQueue", "d8/d50/class_amuse_1_1_r_h_i_1_1_graphic_file_queue.html", null ],
      [ "Amuse::RHI::GraphicObject", "d2/d2f/class_amuse_1_1_r_h_i_1_1_graphic_object.html", [
        [ "Amuse::RHI::Buffer", "d7/d8d/class_amuse_1_1_r_h_i_1_1_buffer.html", null ],
        [ "Amuse::RHI::CommandList", "d7/dc8/class_amuse_1_1_r_h_i_1_1_command_list.html", null ],
        [ "Amuse::RHI::ComputePipelineState", "d9/dab/class_amuse_1_1_r_h_i_1_1_compute_pipeline_state.html", null ],
        [ "Amuse::RHI::DescriptorLayout", "dc/db6/class_amuse_1_1_r_h_i_1_1_descriptor_layout.html", null ],
        [ "Amuse::RHI::DescriptorTable", "d2/d8f/class_amuse_1_1_r_h_i_1_1_descriptor_table.html", null ],
        [ "Amuse::RHI::EventQuery", "d4/d3a/class_amuse_1_1_r_h_i_1_1_event_query.html", null ],
        [ "Amuse::RHI::Fence", "d9/d03/class_amuse_1_1_r_h_i_1_1_fence.html", null ],
        [ "Amuse::RHI::PipelineState", "d6/d59/class_amuse_1_1_r_h_i_1_1_pipeline_state.html", null ],
        [ "Amuse::RHI::RootSignature", "de/d11/class_amuse_1_1_r_h_i_1_1_root_signature.html", null ],
        [ "Amuse::RHI::Sampler", "da/d9b/class_amuse_1_1_r_h_i_1_1_sampler.html", null ],
        [ "Amuse::RHI::Shader", "d7/d68/class_amuse_1_1_r_h_i_1_1_shader.html", null ],
        [ "Amuse::RHI::SwapChain", "d5/df6/class_amuse_1_1_r_h_i_1_1_swap_chain.html", null ],
        [ "Amuse::RHI::Texture", "de/d60/class_amuse_1_1_r_h_i_1_1_texture.html", [
          [ "Amuse::RHI::RenderTexture", "da/d86/class_amuse_1_1_r_h_i_1_1_render_texture.html", null ]
        ] ],
        [ "Amuse::RHI::TimerQuery", "d4/d23/class_amuse_1_1_r_h_i_1_1_timer_query.html", null ],
        [ "Amuse::RHI::VertexLayout", "dc/df3/class_amuse_1_1_r_h_i_1_1_vertex_layout.html", null ]
      ] ]
    ] ],
    [ "Amuse::RHI::RenderPassColorTargetDesc", "d7/dd4/struct_amuse_1_1_r_h_i_1_1_render_pass_color_target_desc.html", null ],
    [ "Amuse::RHI::RenderPassTargetDesc", "d7/d4d/struct_amuse_1_1_r_h_i_1_1_render_pass_target_desc.html", null ],
    [ "Amuse::RHI::RenderTextureDesc", "d4/dc2/struct_amuse_1_1_r_h_i_1_1_render_texture_desc.html", null ],
    [ "Amuse::RHI::RHIConfig", "d8/d50/struct_amuse_1_1_r_h_i_1_1_r_h_i_config.html", null ],
    [ "Amuse::RHI::RHIFeatures", "d7/dd6/struct_amuse_1_1_r_h_i_1_1_r_h_i_features.html", null ],
    [ "Amuse::RHI::RootConstantsDesc", "da/d4a/struct_amuse_1_1_r_h_i_1_1_root_constants_desc.html", null ],
    [ "Amuse::RHI::RootSignatureDesc", "dd/d50/struct_amuse_1_1_r_h_i_1_1_root_signature_desc.html", null ],
    [ "Amuse::Core::Rot", "da/d68/struct_amuse_1_1_core_1_1_rot.html", null ],
    [ "Amuse::RHI::SampleDesc", "dd/d46/struct_amuse_1_1_r_h_i_1_1_sample_desc.html", null ],
    [ "Amuse::RHI::SamplerDesc", "d9/d3d/struct_amuse_1_1_r_h_i_1_1_sampler_desc.html", null ],
    [ "Amuse::RHI::SamplerDescEqual", "d9/d32/struct_amuse_1_1_r_h_i_1_1_sampler_desc_equal.html", null ],
    [ "Amuse::RHI::SamplerDescHasher", "da/dda/struct_amuse_1_1_r_h_i_1_1_sampler_desc_hasher.html", null ],
    [ "Amuse::Core::Schedule< Args >", "da/d73/class_amuse_1_1_core_1_1_schedule.html", null ],
    [ "Amuse::Core::ScheduleBuildError", "d8/de7/struct_amuse_1_1_core_1_1_schedule_build_error.html", null ],
    [ "Amuse::Core::ScheduleBuildResult", "d0/d98/class_amuse_1_1_core_1_1_schedule_build_result.html", null ],
    [ "Amuse::Core::ScheduleBuildSettings", "d5/d45/struct_amuse_1_1_core_1_1_schedule_build_settings.html", null ],
    [ "Amuse::Core::ScheduleBuildWarning", "d9/dd4/struct_amuse_1_1_core_1_1_schedule_build_warning.html", null ],
    [ "Amuse::Core::ScheduleExecutor", "d0/d32/class_amuse_1_1_core_1_1_schedule_executor.html", null ],
    [ "Amuse::Core::ScheduleExecutorConfig", "de/d86/struct_amuse_1_1_core_1_1_schedule_executor_config.html", null ],
    [ "Amuse::Core::ScheduleSet", "dd/dff/class_amuse_1_1_core_1_1_schedule_set.html", null ],
    [ "Amuse::Core::ScopeOutAction", "d3/d65/class_amuse_1_1_core_1_1_scope_out_action.html", null ],
    [ "Amuse::Core::ScopeValue< T, V >", "d3/da5/class_amuse_1_1_core_1_1_scope_value.html", null ],
    [ "Amuse::Core::Segment", "d1/de2/class_amuse_1_1_core_1_1_segment.html", null ],
    [ "Amuse::Core::ServiceBuilderBase", "d5/d79/class_amuse_1_1_core_1_1_service_builder_base.html", [
      [ "Amuse::Core::ServiceBuilder< T >", "d7/d66/class_amuse_1_1_core_1_1_service_builder.html", null ]
    ] ],
    [ "Amuse::Core::ServiceContainer", "d6/d84/class_amuse_1_1_core_1_1_service_container.html", null ],
    [ "Amuse::Core::ServiceInjector", "d6/d5f/class_amuse_1_1_core_1_1_service_injector.html", null ],
    [ "Amuse::RHI::SetDescriptorTableParam", "db/dbb/struct_amuse_1_1_r_h_i_1_1_set_descriptor_table_param.html", null ],
    [ "Amuse::RHI::SetRootConstantsParam", "d7/d56/struct_amuse_1_1_r_h_i_1_1_set_root_constants_param.html", null ],
    [ "Amuse::RHI::ShaderCompileDesc", "d9/d3f/struct_amuse_1_1_r_h_i_1_1_shader_compile_desc.html", null ],
    [ "Amuse::Core::Singleton< T >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", null ],
    [ "Amuse::Core::Singleton< AsyncFileSystem >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::AsyncFileSystem", "d6/d37/class_amuse_1_1_core_1_1_async_file_system.html", null ]
    ] ],
    [ "Amuse::Core::Singleton< Device >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::RHI::Device", "d1/d22/class_amuse_1_1_r_h_i_1_1_device.html", [
        [ "Amuse::RHI::DirectX12Device", "d9/d07/class_amuse_1_1_r_h_i_1_1_direct_x12_device.html", null ]
      ] ]
    ] ],
    [ "Amuse::Core::Singleton< InputModule >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Input::InputModule", "d6/d81/class_amuse_1_1_input_1_1_input_module.html", null ]
    ] ],
    [ "Amuse::Core::Singleton< JobSystem >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::JobSystem", "da/d28/class_amuse_1_1_core_1_1_job_system.html", null ]
    ] ],
    [ "Amuse::Core::Singleton< ThreadPool >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::ThreadPool", "dc/dbe/class_amuse_1_1_core_1_1_thread_pool.html", null ]
    ] ],
    [ "Amuse::Core::Singleton< TypeInfoManager >", "d4/d2f/class_amuse_1_1_core_1_1_singleton.html", [
      [ "Amuse::Core::TypeInfoManager", "da/d48/class_amuse_1_1_core_1_1_type_info_manager.html", null ]
    ] ],
    [ "Amuse::Core::Size", "de/d30/struct_amuse_1_1_core_1_1_size.html", null ],
    [ "Amuse::Core::SourceLocation", "d6/d94/struct_amuse_1_1_core_1_1_source_location.html", null ],
    [ "Amuse::Core::SpanAllocator", "de/dff/class_amuse_1_1_core_1_1_span_allocator.html", null ],
    [ "Amuse::Core::Sphere", "d0/de1/struct_amuse_1_1_core_1_1_sphere.html", null ],
    [ "Amuse::Core::Spline", "d3/de7/class_amuse_1_1_core_1_1_spline.html", null ],
    [ "Amuse::Core::Spline2D", "db/d6b/class_amuse_1_1_core_1_1_spline2_d.html", null ],
    [ "Amuse::Core::StackTrace", "da/d85/struct_amuse_1_1_core_1_1_stack_trace.html", null ],
    [ "Amuse::Core::StackTraceElement", "da/dc0/struct_amuse_1_1_core_1_1_stack_trace_element.html", null ],
    [ "Amuse::RHI::StaticSamplerDesc", "d4/dc3/struct_amuse_1_1_r_h_i_1_1_static_sampler_desc.html", null ],
    [ "STLAllocatorBase", null, [
      [ "Amuse::Core::STLAllocator< T >", "d8/d54/struct_amuse_1_1_core_1_1_s_t_l_allocator.html", null ]
    ] ],
    [ "Amuse::Core::Stream", "df/dc8/class_amuse_1_1_core_1_1_stream.html", [
      [ "Amuse::Core::BinaryStream", "d6/d31/class_amuse_1_1_core_1_1_binary_stream.html", null ],
      [ "Amuse::Core::File", "da/d8e/class_amuse_1_1_core_1_1_file.html", null ]
    ] ],
    [ "Amuse::Core::StringBase< TChar >", "da/d7a/class_amuse_1_1_core_1_1_string_base.html", null ],
    [ "Amuse::Core::StringBase< Char >", "da/d7a/class_amuse_1_1_core_1_1_string_base.html", null ],
    [ "Amuse::Core::StringEncoder", "dc/d28/class_amuse_1_1_core_1_1_string_encoder.html", null ],
    [ "Amuse::Core::StringSplitView", "d3/d99/class_amuse_1_1_core_1_1_string_split_view.html", [
      [ "Amuse::Core::CommaSplitView", "d6/d6a/class_amuse_1_1_core_1_1_comma_split_view.html", null ],
      [ "Amuse::Core::LineBreakSplitView", "dc/d20/class_amuse_1_1_core_1_1_line_break_split_view.html", null ],
      [ "Amuse::Core::TabSplitView", "d4/d55/class_amuse_1_1_core_1_1_tab_split_view.html", null ]
    ] ],
    [ "Amuse::Core::StringViewBase< TChar >", "d1/dcf/class_amuse_1_1_core_1_1_string_view_base.html", null ],
    [ "Amuse::Core::StringViewBase< Char >", "d1/dcf/class_amuse_1_1_core_1_1_string_view_base.html", null ],
    [ "Amuse::RHI::SwapChainDesc", "d6/d44/struct_amuse_1_1_r_h_i_1_1_swap_chain_desc.html", null ],
    [ "Amuse::Core::Swapper< T >", "de/dfa/class_amuse_1_1_core_1_1_swapper.html", null ],
    [ "Amuse::Core::SyncHandleManager< T, Deleter >", "d7/d21/class_amuse_1_1_core_1_1_sync_handle_manager.html", null ],
    [ "Amuse::RHI::SystemDesc", "da/da9/struct_amuse_1_1_r_h_i_1_1_system_desc.html", null ],
    [ "Amuse::Core::TagBuilder", "d5/d17/class_amuse_1_1_core_1_1_tag_builder.html", [
      [ "Amuse::Core::ClassBuilder", "d0/d95/class_amuse_1_1_core_1_1_class_builder.html", [
        [ "Amuse::Core::ClassBuilderTemplate< _T >", "da/d8a/class_amuse_1_1_core_1_1_class_builder_template.html", null ]
      ] ],
      [ "Amuse::Core::EnumBuilder", "d8/ddd/class_amuse_1_1_core_1_1_enum_builder.html", [
        [ "Amuse::Core::EnumBuilderTemplate< _T >", "d1/dcb/class_amuse_1_1_core_1_1_enum_builder_template.html", null ]
      ] ],
      [ "Amuse::Core::PrimitiveBuilder", "d7/d60/class_amuse_1_1_core_1_1_primitive_builder.html", [
        [ "Amuse::Core::PrimitiveBuilderTemplate< _T >", "db/d67/class_amuse_1_1_core_1_1_primitive_builder_template.html", null ]
      ] ]
    ] ],
    [ "Amuse::Core::TagInfo", "da/d3a/struct_amuse_1_1_core_1_1_tag_info.html", [
      [ "Amuse::Core::ConstructorInfo", "d6/d8e/struct_amuse_1_1_core_1_1_constructor_info.html", null ],
      [ "Amuse::Core::EnumElementInfo", "d2/de7/struct_amuse_1_1_core_1_1_enum_element_info.html", null ],
      [ "Amuse::Core::MethodInfo", "d5/d20/struct_amuse_1_1_core_1_1_method_info.html", null ],
      [ "Amuse::Core::PropertyInfo", "d7/dd1/struct_amuse_1_1_core_1_1_property_info.html", null ],
      [ "Amuse::Core::TypeInfo", "d3/d31/struct_amuse_1_1_core_1_1_type_info.html", null ]
    ] ],
    [ "Amuse::Core::Task", "db/d92/class_amuse_1_1_core_1_1_task.html", null ],
    [ "Amuse::Core::TaskGroup", "de/d28/class_amuse_1_1_core_1_1_task_group.html", null ],
    [ "Amuse::Core::TCPClient", "da/dce/class_amuse_1_1_core_1_1_t_c_p_client.html", null ],
    [ "Amuse::Core::TCPServer", "d1/d28/class_amuse_1_1_core_1_1_t_c_p_server.html", null ],
    [ "Amuse::Platform::TextInput", "dc/d36/class_amuse_1_1_platform_1_1_text_input.html", null ],
    [ "Amuse::RHI::TextureBarrier", "dc/d9f/struct_amuse_1_1_r_h_i_1_1_texture_barrier.html", null ],
    [ "Amuse::RHI::TextureCopyRegion", "db/dce/struct_amuse_1_1_r_h_i_1_1_texture_copy_region.html", null ],
    [ "Amuse::RHI::GraphicFileRequest::TextureDesc", "d3/d65/struct_amuse_1_1_r_h_i_1_1_graphic_file_request_1_1_texture_desc.html", null ],
    [ "Amuse::RHI::TextureDesc", "df/d82/struct_amuse_1_1_r_h_i_1_1_texture_desc.html", null ],
    [ "Amuse::RHI::TextureFormatUtility", "d7/d71/class_amuse_1_1_r_h_i_1_1_texture_format_utility.html", null ],
    [ "Amuse::RHI::GraphicFileRequest::TextureSequenceDesc", "df/d0a/struct_amuse_1_1_r_h_i_1_1_graphic_file_request_1_1_texture_sequence_desc.html", null ],
    [ "Amuse::RHI::TextureSubresource", "d2/db4/struct_amuse_1_1_r_h_i_1_1_texture_subresource.html", null ],
    [ "Amuse::RHI::TextureSubresourceRange", "d3/df1/struct_amuse_1_1_r_h_i_1_1_texture_subresource_range.html", null ],
    [ "Amuse::RHI::TextureViewDesc", "d5/d16/struct_amuse_1_1_r_h_i_1_1_texture_view_desc.html", null ],
    [ "Amuse::Core::ThreadDesc", "de/dbb/struct_amuse_1_1_core_1_1_thread_desc.html", null ],
    [ "Amuse::Core::TimeSpan", "db/df5/class_amuse_1_1_core_1_1_time_span.html", null ],
    [ "Amuse::Core::TLSFBlock", "d4/d6a/struct_amuse_1_1_core_1_1_t_l_s_f_block.html", null ],
    [ "Amuse::Core::Transform", "d0/d24/class_amuse_1_1_core_1_1_transform.html", null ],
    [ "Amuse::Core::Transition", "d4/d1b/class_amuse_1_1_core_1_1_transition.html", null ],
    [ "Amuse::Core::Triangle", "d9/ddf/class_amuse_1_1_core_1_1_triangle.html", null ],
    [ "std::true_type", null, [
      [ "Amuse::Core::is_map< HashMap< TKey, TValue > >", "dc/d63/struct_amuse_1_1_core_1_1is__map_3_01_hash_map_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
      [ "Amuse::Core::is_map< Map< TKey, TValue > >", "d8/da4/struct_amuse_1_1_core_1_1is__map_3_01_map_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< Array< T, N > >", "d4/d8c/struct_amuse_1_1_core_1_1is__sequence_3_01_array_3_01_t_00_01_n_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< HashSet< T, ALLOCATOR > >", "dd/d3c/struct_amuse_1_1_core_1_1is__sequence_3_01_hash_set_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< List< T, ALLOCATOR > >", "d6/d92/struct_amuse_1_1_core_1_1is__sequence_3_01_list_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< Set< T, ALLOCATOR > >", "d1/dfc/struct_amuse_1_1_core_1_1is__sequence_3_01_set_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ],
      [ "Amuse::Core::is_sequence< T[N]>", "d6/d8f/struct_amuse_1_1_core_1_1is__sequence_3_01_t_0f_n_0e_4.html", null ],
      [ "Amuse::Core::is_sequence< Vector< T, ALLOCATOR > >", "da/d1b/struct_amuse_1_1_core_1_1is__sequence_3_01_vector_3_01_t_00_01_a_l_l_o_c_a_t_o_r_01_4_01_4.html", null ]
    ] ],
    [ "Amuse::Core::Type", "dd/db0/class_amuse_1_1_core_1_1_type.html", null ],
    [ "Amuse::Core::TypedPointer", "d7/dd5/class_amuse_1_1_core_1_1_typed_pointer.html", null ],
    [ "Amuse::Core::TypeRegister", "d6/d66/struct_amuse_1_1_core_1_1_type_register.html", null ],
    [ "Amuse::Core::TypeRegisterTemplate< T >", "d3/d48/struct_amuse_1_1_core_1_1_type_register_template.html", null ],
    [ "Amuse::Core::UUID", "d0/d96/struct_amuse_1_1_core_1_1_u_u_i_d.html", null ],
    [ "Amuse::Core::Vec2", "df/d62/struct_amuse_1_1_core_1_1_vec2.html", null ],
    [ "Amuse::Core::Vec3", "d7/d02/struct_amuse_1_1_core_1_1_vec3.html", null ],
    [ "Amuse::Core::Vec4", "da/da9/struct_amuse_1_1_core_1_1_vec4.html", null ],
    [ "Amuse::RHI::VertexAttribute", "db/df6/struct_amuse_1_1_r_h_i_1_1_vertex_attribute.html", null ],
    [ "Amuse::RHI::VertexLayoutDesc", "dc/dd6/struct_amuse_1_1_r_h_i_1_1_vertex_layout_desc.html", null ],
    [ "Amuse::RHI::VideoCard", "dd/d49/struct_amuse_1_1_r_h_i_1_1_video_card.html", null ],
    [ "Amuse::RHI::VideoOutput", "df/db9/struct_amuse_1_1_r_h_i_1_1_video_output.html", null ],
    [ "Amuse::RHI::VideoOutputMode", "dd/de9/struct_amuse_1_1_r_h_i_1_1_video_output_mode.html", null ],
    [ "Amuse::Core::Viewport", "d0/d65/struct_amuse_1_1_core_1_1_viewport.html", null ],
    [ "Amuse::RHI::VulkanRHIConfig", "d4/d78/struct_amuse_1_1_r_h_i_1_1_vulkan_r_h_i_config.html", null ],
    [ "Amuse::Platform::WindowDesc", "d9/d54/struct_amuse_1_1_platform_1_1_window_desc.html", null ],
    [ "Amuse::Platform::WindowEventArgs", "de/dfb/struct_amuse_1_1_platform_1_1_window_event_args.html", null ],
    [ "Amuse::Core::XmlNode", "d9/d2d/class_amuse_1_1_core_1_1_xml_node.html", [
      [ "Amuse::Core::Xml", "dd/d97/class_amuse_1_1_core_1_1_xml.html", null ]
    ] ],
    [ "Amuse::Core::YesNo< Tag >", "d1/d0c/class_amuse_1_1_core_1_1_yes_no.html", null ]
];